// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Organization {
    /// ID is the unique identifier of the organization.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Details about the organizations' creation and change date.
    #[prost(message, optional, tag="2")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    /// Current state of the organization, for example active, inactive or deleted.
    #[prost(enumeration="OrganizationState", tag="3")]
    pub state: i32,
    /// Name of the organization.
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    /// Organization Domain used in the organization.
    #[prost(string, tag="5")]
    pub primary_domain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Domain {
    /// OrganizationID is the unique identifier of the organization the domain belongs to.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Domain is the fully qualified domain name.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
    /// IsVerified is a boolean flag indicating if the domain has been verified.
    #[prost(bool, tag="3")]
    pub is_verified: bool,
    /// IsPrimary is a boolean flag indicating if the domain is the Organization Domain of the organization.
    #[prost(bool, tag="4")]
    pub is_primary: bool,
    /// ValidationType indicates the protocol used to validate the domain ownership.
    #[prost(enumeration="DomainValidationType", tag="5")]
    pub validation_type: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrganizationState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
    Removed = 3,
}
impl OrganizationState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORGANIZATION_STATE_UNSPECIFIED",
            Self::Active => "ORGANIZATION_STATE_ACTIVE",
            Self::Inactive => "ORGANIZATION_STATE_INACTIVE",
            Self::Removed => "ORGANIZATION_STATE_REMOVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORGANIZATION_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "ORGANIZATION_STATE_ACTIVE" => Some(Self::Active),
            "ORGANIZATION_STATE_INACTIVE" => Some(Self::Inactive),
            "ORGANIZATION_STATE_REMOVED" => Some(Self::Removed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DomainValidationType {
    Unspecified = 0,
    /// HTTP validation requires you to host a specific file on your domain.
    /// This file is checked by us to verify that you own the domain.
    Http = 1,
    /// DNS validation requires you to create a specific TXT record in your domain's DNS settings.
    /// This record is checked by us to verify that you own the domain.
    Dns = 2,
}
impl DomainValidationType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOMAIN_VALIDATION_TYPE_UNSPECIFIED",
            Self::Http => "DOMAIN_VALIDATION_TYPE_HTTP",
            Self::Dns => "DOMAIN_VALIDATION_TYPE_DNS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOMAIN_VALIDATION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DOMAIN_VALIDATION_TYPE_HTTP" => Some(Self::Http),
            "DOMAIN_VALIDATION_TYPE_DNS" => Some(Self::Dns),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchQuery {
    #[prost(oneof="search_query::Query", tags="1, 2, 3, 4, 5")]
    pub query: ::core::option::Option<search_query::Query>,
}
/// Nested message and enum types in `SearchQuery`.
pub mod search_query {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        /// Filter organizations by their name.
        #[prost(message, tag="1")]
        NameQuery(super::OrganizationNameQuery),
        /// Filter organizations by their domain.
        #[prost(message, tag="2")]
        DomainQuery(super::OrganizationDomainQuery),
        /// Filter organizations by their state.
        #[prost(message, tag="3")]
        StateQuery(super::OrganizationStateQuery),
        /// Filter organizations by their id.
        #[prost(message, tag="4")]
        IdQuery(super::OrganizationIdQuery),
        /// Filter for the default organization.
        #[prost(message, tag="5")]
        DefaultQuery(super::DefaultOrganizationQuery),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrganizationNameQuery {
    /// Name of the organization.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Defines which text equality method is used.
    #[prost(enumeration="super::super::object::v2::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrganizationDomainQuery {
    /// Domain used in organization, not necessary primary domain.
    #[prost(string, tag="1")]
    pub domain: ::prost::alloc::string::String,
    /// Defines which text equality method is used.
    #[prost(enumeration="super::super::object::v2::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrganizationStateQuery {
    /// Current state of the organization.
    #[prost(enumeration="OrganizationState", tag="1")]
    pub state: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrganizationIdQuery {
    /// Unique identifier of the organization.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DefaultOrganizationQuery {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainSearchFilter {
    #[prost(oneof="domain_search_filter::Filter", tags="1")]
    pub filter: ::core::option::Option<domain_search_filter::Filter>,
}
/// Nested message and enum types in `DomainSearchFilter`.
pub mod domain_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter Organization Domains by their domain name.
        #[prost(message, tag="1")]
        DomainFilter(super::OrganizationDomainQuery),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrganizationFieldName {
    Unspecified = 0,
    Name = 1,
    CreationDate = 2,
}
impl OrganizationFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORGANIZATION_FIELD_NAME_UNSPECIFIED",
            Self::Name => "ORGANIZATION_FIELD_NAME_NAME",
            Self::CreationDate => "ORGANIZATION_FIELD_NAME_CREATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORGANIZATION_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "ORGANIZATION_FIELD_NAME_NAME" => Some(Self::Name),
            "ORGANIZATION_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DomainFieldName {
    Unspecified = 0,
    Name = 1,
    CreationDate = 2,
}
impl DomainFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOMAIN_FIELD_NAME_UNSPECIFIED",
            Self::Name => "DOMAIN_FIELD_NAME_NAME",
            Self::CreationDate => "DOMAIN_FIELD_NAME_CREATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOMAIN_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "DOMAIN_FIELD_NAME_NAME" => Some(Self::Name),
            "DOMAIN_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddOrganizationRequest {
    /// Name is the unique name of the organization to be created.
    /// This must be unique across the instance.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Specify users to be assigned as organization admins.
    /// If no users are specified here, the organization will be created without any admin users.
    /// The organization can still be managed by any instance administrator.
    /// If no roles are specified for a user, they will be assigned the role ORG_OWNER.
    #[prost(message, repeated, tag="2")]
    pub admins: ::prost::alloc::vec::Vec<add_organization_request::Admin>,
    /// OrganizationID is the unique identifier of the organization. This field is optional.
    /// If omitted, the system will generate one,
    /// which is the recommended way. The generated ID will be returned in the response.
    #[prost(string, optional, tag="4")]
    pub organization_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Optionally, set a unique id for the organization. If omitted, the system will generate one,
    /// which is the recommended way. The generated ID will be returned in the response.
    ///
    /// Deprecated: use 'organization_id' field instead.
    /// If both org_id and organization_id are set, organization_id will take precedence.
    #[deprecated]
    #[prost(string, optional, tag="3")]
    pub org_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `AddOrganizationRequest`.
pub mod add_organization_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Admin {
        /// specify Org Member Roles for the provided user (default is ORG_OWNER if roles are empty)
        #[prost(string, repeated, tag="3")]
        pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(oneof="admin::UserType", tags="1, 2")]
        pub user_type: ::core::option::Option<admin::UserType>,
    }
    /// Nested message and enum types in `Admin`.
    pub mod admin {
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum UserType {
            #[prost(string, tag="1")]
            UserId(::prost::alloc::string::String),
            #[prost(message, tag="2")]
            Human(super::super::super::super::user::v2::AddHumanUserRequest),
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddOrganizationResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub created_admins: ::prost::alloc::vec::Vec<add_organization_response::CreatedAdmin>,
}
/// Nested message and enum types in `AddOrganizationResponse`.
pub mod add_organization_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct CreatedAdmin {
        #[prost(string, tag="1")]
        pub user_id: ::prost::alloc::string::String,
        #[prost(string, optional, tag="2")]
        pub email_code: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag="3")]
        pub phone_code: ::core::option::Option<::prost::alloc::string::String>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateOrganizationRequest {
    /// OrganizationID is the unique identifier of the organization to be updated.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Name is the new name for the organization to be set.
    /// Note that since the name is used to generate the organization's default domain,
    /// changing the name will also change the domain.
    /// Additionally, if the domain is used as suffix for user logins,
    /// their login names will also change accordingly.
    /// It will not affect any Organization Domains added to the organization.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateOrganizationResponse {
    /// ChangeDate is the timestamp of the update to the organization.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationsRequest {
    /// list limitations and ordering
    #[prost(message, optional, tag="1")]
    pub query: ::core::option::Option<super::super::object::v2::ListQuery>,
    /// the field the result is sorted
    #[prost(enumeration="OrganizationFieldName", tag="2")]
    pub sorting_column: i32,
    /// criteria the client is looking for
    #[prost(message, repeated, tag="3")]
    pub queries: ::prost::alloc::vec::Vec<SearchQuery>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationsResponse {
    /// Details of organizations results.
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::ListDetails>,
    /// The sorting columns the result is sorted.
    #[prost(enumeration="OrganizationFieldName", tag="2")]
    pub sorting_column: i32,
    /// The Result is a list of organizations matching the query.
    #[prost(message, repeated, tag="3")]
    pub result: ::prost::alloc::vec::Vec<Organization>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationRequest {
    /// OrganizationID is the unique identifier of the organization to be deleted.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationResponse {
    /// DeletionDate is the timestamp of the deletion of the organization.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateOrganizationRequest {
    /// OrganizationID is the unique identifier of the organization to be deactivated.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateOrganizationResponse {
    /// ChangeDate is the timestamp of the deactivation of the organization.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateOrganizationRequest {
    /// OrganizationID is the unique identifier of the organization to be activated.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateOrganizationResponse {
    /// ChangeDate is the timestamp of the activation of the organization.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddOrganizationDomainRequest {
    /// OrganizationID is the unique identifier of the organization to which the domain is to be added.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Domain is the full qualified domain name to be added to the organization.
    /// Note that the domain has to be unique across the instance.
    /// Depending on the settings, you might have to verify the domain before it can be used.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddOrganizationDomainResponse {
    /// CreationDate is the timestamp when the Organization Domain was created.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationDomainsRequest {
    /// OrganizationID is the unique identifier of the organization from which the domains are to be listed.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// List limitations and ordering.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// Filters define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<DomainSearchFilter>,
    /// SortingColumn is the field the result is sorted by.
    /// Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="DomainFieldName", tag="4")]
    pub sorting_column: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationDomainsResponse {
    /// Pagination of the organizations domain results.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// Domains is a list of fully qualified domain names registered to the organization matching the query.
    #[prost(message, repeated, tag="2")]
    pub domains: ::prost::alloc::vec::Vec<Domain>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationDomainRequest {
    /// OrganizationID is the unique identifier of the organization from which the domain is to be deleted.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Domain is the full qualified domain name to be deleted from the organization.
    /// Note that if the domain is used as suffix for user logins,
    /// those users will not be able to log in anymore. They have to use another domain instead.
    /// Also if the domain was used for domain discovery,
    /// users will not be able to find the organization by the domain anymore.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationDomainResponse {
    /// DeletionDate is the timestamp of the deletion of the Organization Domain.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenerateOrganizationDomainValidationRequest {
    /// OrganizationID is the unique identifier of the organization for which the domain validation is to be generated.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Domain is the full qualified domain name for which the validation is to be generated.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
    /// Type is the domain validation type to be generated.
    /// Depending on the type, you will have to add a DNS record or a file to your webserver.
    /// Make sure that the challenge is reachable via the chosen method.
    /// The validation has to be done within one hour, otherwise the token will expire and you will have to generate a new one.
    /// After you have added the record or the file, you can verify the domain via the VerifyOrganizationDomain endpoint.
    /// You can check the status of the domain via the ListOrganizationDomains endpoint.
    /// The domain will be marked as verified after a successful verification.
    #[prost(enumeration="DomainValidationType", tag="3")]
    pub r#type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenerateOrganizationDomainValidationResponse {
    /// Token is a verification token that needs to be added to the DNS records or as a file to the webserver.
    /// Zitadel will check for this token to verify the domain.
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    /// URL is the location where the token needs to be placed for HTTP challenge.
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyOrganizationDomainRequest {
    /// Organization ID is the unique identifier of the organization whose domain is to be verified.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Domain is the full qualified domain name to be verified.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyOrganizationDomainResponse {
    /// ChangeDate is the timestamp of the verification of the Organization Domain.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    /// Key is identifier of the metadata entry.
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    /// Value is the values of the metadata entry.
    #[prost(bytes="vec", tag="2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetOrganizationMetadataRequest {
    /// Organization ID is the unique identifier of the organization whose metadata is to be set.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Metadata is a list of metadata entries to set.
    #[prost(message, repeated, tag="2")]
    pub metadata: ::prost::alloc::vec::Vec<Metadata>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetOrganizationMetadataResponse {
    /// The timestamp of the update of the organization metadata.
    #[prost(message, optional, tag="1")]
    pub set_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationMetadataRequest {
    /// Organization ID is the unique identifier of the organization whose metadata is to be listed.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// List limitations and ordering.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// Filters define the criteria to query the metadata for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<super::super::metadata::v2::MetadataSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationMetadataResponse {
    /// Pagination of the Organizations metadata results.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// Metadata is a list of organization metadata that matched the query.
    #[prost(message, repeated, tag="2")]
    pub metadata: ::prost::alloc::vec::Vec<super::super::metadata::v2::Metadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationMetadataRequest {
    /// Organization ID is the unique identifier of the organization whose metadata is to be deleted.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Keys are the organization metadata entries to be deleted by their key.
    #[prost(string, repeated, tag="2")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationMetadataResponse {
    /// DeletionDate is the timestamp of the deletion of the organization metadata.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
include!("zitadel.org.v2.tonic.rs");
// @@protoc_insertion_point(module)