// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="2")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(string, tag="3")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetadataSearchFilter {
    #[prost(oneof="metadata_search_filter::Filter", tags="1")]
    pub filter: ::core::option::Option<metadata_search_filter::Filter>,
}
/// Nested message and enum types in `MetadataSearchFilter`.
pub mod metadata_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        #[prost(message, tag="1")]
        KeyFilter(super::MetadataKeyFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetadataKeyFilter {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::filter::v2::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetadataValueFilter {
    #[prost(bytes="vec", tag="1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration="super::super::filter::v2::ByteFilterMethod", tag="2")]
    pub method: i32,
}
// @@protoc_insertion_point(module)
