// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Member {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub details: ::core::option::Option<super::super::v1::ObjectDetails>,
    #[prost(string, repeated, tag="3")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub preferred_login_name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub first_name: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub last_name: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::user::v1::Type", tag="10")]
    pub user_type: i32,
    /// The organization the user belong to.  
    #[prost(string, tag="11")]
    pub user_resource_owner: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchQuery {
    #[prost(oneof="search_query::Query", tags="1, 2, 3, 4")]
    pub query: ::core::option::Option<search_query::Query>,
}
/// Nested message and enum types in `SearchQuery`.
pub mod search_query {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        #[prost(message, tag="1")]
        FirstNameQuery(super::FirstNameQuery),
        #[prost(message, tag="2")]
        LastNameQuery(super::LastNameQuery),
        #[prost(message, tag="3")]
        EmailQuery(super::EmailQuery),
        #[prost(message, tag="4")]
        UserIdQuery(super::UserIdQuery),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FirstNameQuery {
    #[prost(string, tag="1")]
    pub first_name: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::v1::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LastNameQuery {
    #[prost(string, tag="1")]
    pub last_name: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::v1::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmailQuery {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::v1::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserIdQuery {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MemberFieldColumnName {
    MemberFieldNameUnspecified = 0,
    MemberFieldNameUserId = 1,
    MemberFieldNameCreationDate = 2,
    MemberFieldNameChangeDate = 3,
    MemberFieldNameUserResourceOwner = 4,
}
impl MemberFieldColumnName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MemberFieldNameUnspecified => "MEMBER_FIELD_NAME_UNSPECIFIED",
            Self::MemberFieldNameUserId => "MEMBER_FIELD_NAME_USER_ID",
            Self::MemberFieldNameCreationDate => "MEMBER_FIELD_NAME_CREATION_DATE",
            Self::MemberFieldNameChangeDate => "MEMBER_FIELD_NAME_CHANGE_DATE",
            Self::MemberFieldNameUserResourceOwner => "MEMBER_FIELD_NAME_USER_RESOURCE_OWNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MEMBER_FIELD_NAME_UNSPECIFIED" => Some(Self::MemberFieldNameUnspecified),
            "MEMBER_FIELD_NAME_USER_ID" => Some(Self::MemberFieldNameUserId),
            "MEMBER_FIELD_NAME_CREATION_DATE" => Some(Self::MemberFieldNameCreationDate),
            "MEMBER_FIELD_NAME_CHANGE_DATE" => Some(Self::MemberFieldNameChangeDate),
            "MEMBER_FIELD_NAME_USER_RESOURCE_OWNER" => Some(Self::MemberFieldNameUserResourceOwner),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
