// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Organization {
    /// Unique identifier of the organization.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// The timestamp of the organization was created.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    ///   The timestamp of the verification of the Organization Domain.
    #[prost(message, optional, tag="3")]
    pub changed_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Current state of the organization, for example active, inactive and deleted.
    #[prost(enumeration="OrgState", tag="4")]
    pub state: i32,
    /// Name of the organization.
    #[prost(string, tag="5")]
    pub name: ::prost::alloc::string::String,
    /// Organization Domain used in the organization.
    #[prost(string, tag="6")]
    pub primary_domain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrganizationSearchFilter {
    #[prost(oneof="organization_search_filter::Filter", tags="1, 2, 3, 4")]
    pub filter: ::core::option::Option<organization_search_filter::Filter>,
}
/// Nested message and enum types in `OrganizationSearchFilter`.
pub mod organization_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        #[prost(message, tag="1")]
        NameFilter(super::OrgNameFilter),
        #[prost(message, tag="2")]
        DomainFilter(super::OrgDomainFilter),
        #[prost(message, tag="3")]
        StateFilter(super::OrgStateFilter),
        #[prost(message, tag="4")]
        IdFilter(super::OrgIdFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrgNameFilter {
    /// Organization name.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Defines which text equality method is used.
    #[prost(enumeration="super::super::object::v2beta::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrgDomainFilter {
    /// The domain.
    #[prost(string, tag="1")]
    pub domain: ::prost::alloc::string::String,
    /// Defines which text equality method is used.
    #[prost(enumeration="super::super::object::v2beta::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrgStateFilter {
    /// Current state of the organization.
    #[prost(enumeration="OrgState", tag="1")]
    pub state: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrgIdFilter {
    /// The Organization id.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// from proto/zitadel/org.proto
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainSearchFilter {
    #[prost(oneof="domain_search_filter::Filter", tags="1")]
    pub filter: ::core::option::Option<domain_search_filter::Filter>,
}
/// Nested message and enum types in `DomainSearchFilter`.
pub mod domain_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        #[prost(message, tag="1")]
        DomainNameFilter(super::DomainNameFilter),
    }
}
/// from proto/zitadel/org.proto
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainNameFilter {
    /// The domain.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Defines which text equality method is used.
    #[prost(enumeration="super::super::object::v2beta::TextQueryMethod", tag="2")]
    pub method: i32,
}
/// from proto/zitadel/org.proto
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Domain {
    /// The Organization id.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// The domain name.
    #[prost(string, tag="2")]
    pub domain_name: ::prost::alloc::string::String,
    /// Defines if the domain is verified.
    #[prost(bool, tag="3")]
    pub is_verified: bool,
    /// Defines if the domain is the Organization Domain.
    #[prost(bool, tag="4")]
    pub is_primary: bool,
    /// Defines the protocol the domain was validated with.
    #[prost(enumeration="DomainValidationType", tag="5")]
    pub validation_type: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrgState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
    Removed = 3,
}
impl OrgState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORG_STATE_UNSPECIFIED",
            Self::Active => "ORG_STATE_ACTIVE",
            Self::Inactive => "ORG_STATE_INACTIVE",
            Self::Removed => "ORG_STATE_REMOVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORG_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "ORG_STATE_ACTIVE" => Some(Self::Active),
            "ORG_STATE_INACTIVE" => Some(Self::Inactive),
            "ORG_STATE_REMOVED" => Some(Self::Removed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrgFieldName {
    Unspecified = 0,
    Name = 1,
    CreationDate = 2,
}
impl OrgFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORG_FIELD_NAME_UNSPECIFIED",
            Self::Name => "ORG_FIELD_NAME_NAME",
            Self::CreationDate => "ORG_FIELD_NAME_CREATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORG_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "ORG_FIELD_NAME_NAME" => Some(Self::Name),
            "ORG_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            _ => None,
        }
    }
}
/// from proto/zitadel/org.proto
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DomainValidationType {
    Unspecified = 0,
    Http = 1,
    Dns = 2,
}
impl DomainValidationType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOMAIN_VALIDATION_TYPE_UNSPECIFIED",
            Self::Http => "DOMAIN_VALIDATION_TYPE_HTTP",
            Self::Dns => "DOMAIN_VALIDATION_TYPE_DNS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOMAIN_VALIDATION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DOMAIN_VALIDATION_TYPE_HTTP" => Some(Self::Http),
            "DOMAIN_VALIDATION_TYPE_DNS" => Some(Self::Dns),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrganizationRequest {
    /// name of the Organization to be created.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Optionally set your own id unique for the organization.
    #[prost(string, optional, tag="2")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
    /// Additional Admins for the Organization.
    #[prost(message, repeated, tag="3")]
    pub admins: ::prost::alloc::vec::Vec<create_organization_request::Admin>,
}
/// Nested message and enum types in `CreateOrganizationRequest`.
pub mod create_organization_request {
    /// The Admin for the newly created Organization.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Admin {
        /// specify Organization Member Roles for the provided user (default is ORG_OWNER if roles are empty)
        #[prost(string, repeated, tag="3")]
        pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(oneof="admin::UserType", tags="1, 2")]
        pub user_type: ::core::option::Option<admin::UserType>,
    }
    /// Nested message and enum types in `Admin`.
    pub mod admin {
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum UserType {
            #[prost(string, tag="1")]
            UserId(::prost::alloc::string::String),
            #[prost(message, tag="2")]
            Human(super::super::super::super::user::v2beta::AddHumanUserRequest),
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreatedAdmin {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub email_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub phone_code: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignedAdmin {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrganizationAdmin {
    /// The admins created/assigned for the Organization.
    #[prost(oneof="organization_admin::OrganizationAdmin", tags="1, 2")]
    pub organization_admin: ::core::option::Option<organization_admin::OrganizationAdmin>,
}
/// Nested message and enum types in `OrganizationAdmin`.
pub mod organization_admin {
    /// The admins created/assigned for the Organization.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OrganizationAdmin {
        #[prost(message, tag="1")]
        CreatedAdmin(super::CreatedAdmin),
        #[prost(message, tag="2")]
        AssignedAdmin(super::AssignedAdmin),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrganizationResponse {
    /// The timestamp of the organization was created.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Organization ID of the newly created organization.
    #[prost(string, tag="2")]
    pub id: ::prost::alloc::string::String,
    /// The admins created/assigned for the Organization
    #[prost(message, repeated, tag="3")]
    pub organization_admins: ::prost::alloc::vec::Vec<OrganizationAdmin>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateOrganizationRequest {
    /// Organization Id for the Organization to be updated
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// New Name for the Organization to be updated
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateOrganizationResponse {
    /// The timestamp of the update to the organization.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationsRequest {
    /// List limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationRequest>,
    /// the field the result is sorted
    #[prost(enumeration="OrgFieldName", tag="2")]
    pub sorting_column: i32,
    /// Define the criteria to query for.
    /// repeated ProjectRoleQuery filters = 4;
    #[prost(message, repeated, tag="3")]
    pub filter: ::prost::alloc::vec::Vec<OrganizationSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationsResponse {
    /// Pagination of the Organizations results
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationResponse>,
    /// The Organizations requested
    #[prost(message, repeated, tag="2")]
    pub organizations: ::prost::alloc::vec::Vec<Organization>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationRequest {
    /// Organization Id for the Organization to be deleted
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationResponse {
    /// The timestamp of the deletion of the organization.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateOrganizationRequest {
    /// Organization Id for the Organization to be deactivated
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateOrganizationResponse {
    /// The timestamp of the deactivation of the organization.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateOrganizationRequest {
    /// Organization Id for the Organization to be activated
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateOrganizationResponse {
    /// The timestamp of the activation of the organization.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddOrganizationDomainRequest {
    /// Organization Id for the Organization for which the domain is to be added to.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// The domain you want to add to the organization.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddOrganizationDomainResponse {
    /// The timestamp of the organization was created.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationDomainsRequest {
    /// Organization Id for the Organization which domains are to be listed.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// List limitations and ordering.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationRequest>,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<DomainSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationDomainsResponse {
    /// Pagination of the Organizations domain results.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationResponse>,
    /// The domains requested.
    #[prost(message, repeated, tag="2")]
    pub domains: ::prost::alloc::vec::Vec<Domain>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationDomainRequest {
    /// Organization Id for the Organization which domain is to be deleted.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationDomainResponse {
    /// The timestamp of the deletion of the Organization Domain.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenerateOrganizationDomainValidationRequest {
    /// Organization Id for the Organization which doman to be validated.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// The domain which to be deleted.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
    #[prost(enumeration="DomainValidationType", tag="3")]
    pub r#type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenerateOrganizationDomainValidationResponse {
    /// The token verify domain.
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    /// URL used to verify the domain.
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyOrganizationDomainRequest {
    /// Organization Id for the Organization doman to be verified.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Organization Id for the Organization doman to be verified.
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyOrganizationDomainResponse {
    /// The timestamp of the verification of the Organization Domain.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    /// Key in the metadata key/value pair.
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    /// Value in the metadata key/value pair.
    #[prost(bytes="vec", tag="2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetOrganizationMetadataRequest {
    /// Organization Id for the Organization doman to be verified.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Metadata to set.
    #[prost(message, repeated, tag="2")]
    pub metadata: ::prost::alloc::vec::Vec<Metadata>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetOrganizationMetadataResponse {
    /// The timestamp of the update of the organization metadata.
    #[prost(message, optional, tag="1")]
    pub set_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationMetadataRequest {
    /// Organization ID of Orgalization which metadata is to be listed.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// List limitations and ordering.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationRequest>,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filter: ::prost::alloc::vec::Vec<super::super::metadata::v2beta::MetadataQuery>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationMetadataResponse {
    /// Pagination of the Organizations metadata results.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationResponse>,
    /// The Organization metadata requested.
    #[prost(message, repeated, tag="2")]
    pub metadata: ::prost::alloc::vec::Vec<super::super::metadata::v2beta::Metadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationMetadataRequest {
    /// Organization ID of Orgalization which metadata is to be deleted is stored on.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// The keys for the Organization metadata to be deleted.
    #[prost(string, repeated, tag="2")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationMetadataResponse {
    /// The timestamp of the deletiion of the organization metadata.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
include!("zitadel.org.v2beta.tonic.rs");
// @@protoc_insertion_point(module)