// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectGrant {
    /// The unique identifier of the organization which granted the project to the granted_organization_id.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// The timestamp of the granted project creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The timestamp of the last change to the granted project (e.g. creation, activation, deactivation).
    #[prost(message, optional, tag="3")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The ID of the organization the project is granted to.
    #[prost(string, tag="4")]
    pub granted_organization_id: ::prost::alloc::string::String,
    /// The name of the organization the project is granted to.
    #[prost(string, tag="5")]
    pub granted_organization_name: ::prost::alloc::string::String,
    /// The roles granted to the organization for self-management of the project.
    #[prost(string, repeated, tag="6")]
    pub granted_role_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The ID of the granted project.
    #[prost(string, tag="7")]
    pub project_id: ::prost::alloc::string::String,
    /// The name of the granted project.
    #[prost(string, tag="8")]
    pub project_name: ::prost::alloc::string::String,
    /// Describes the current state of the granted project.
    #[prost(enumeration="ProjectGrantState", tag="9")]
    pub state: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Project {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// OrganizationID is the unique identifier of the organization the project belongs to.
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    /// CreationDate is the timestamp of the project creation.
    #[prost(message, optional, tag="3")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// ChangeDate is the timestamp of the last change to the project (e.g. creation, activation, deactivation).
    #[prost(message, optional, tag="4")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Name is the name of the project. This might be presented to users, e.g. in sign-in flows.
    #[prost(string, tag="5")]
    pub name: ::prost::alloc::string::String,
    /// State describes the current state of the project.
    #[prost(enumeration="ProjectState", tag="6")]
    pub state: i32,
    /// ProjectRoleAssertion is a boolean flag that describes if the roles of the user should be added to the token.
    #[prost(bool, tag="7")]
    pub project_role_assertion: bool,
    /// AuthorizationRequired is a boolean flag that can be enabled to check if a user has
    /// an authorization to use this project assigned when login into an application of this project.
    #[prost(bool, tag="8")]
    pub authorization_required: bool,
    /// ProjectAccessRequired is a boolean flag that can be enabled to check if the organization of the user,
    /// that is trying to log in, has access to this project (either owns the project or is granted).
    #[prost(bool, tag="9")]
    pub project_access_required: bool,
    /// PrivateLabelingSetting defines from where the private labeling should be triggered.
    #[prost(enumeration="PrivateLabelingSetting", tag="10")]
    pub private_labeling_setting: i32,
    /// GrantedOrganizationID is the ID of the organization the project is granted to.
    /// In case the project is not granted, this field is unset.
    #[prost(string, optional, tag="12")]
    pub granted_organization_id: ::core::option::Option<::prost::alloc::string::String>,
    /// GrantedOrganizationName is the name of the organization the project is granted to.
    /// In case the project is not granted, this field is unset.
    #[prost(string, optional, tag="13")]
    pub granted_organization_name: ::core::option::Option<::prost::alloc::string::String>,
    /// GrantedProjectState describes the current state of the granted project.
    /// In case the project is not granted, this field is set to GrantedProjectState.GRANTED_PROJECT_STATE_UNSPECIFIED.
    #[prost(enumeration="GrantedProjectState", tag="14")]
    pub granted_state: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectSearchFilter {
    #[prost(oneof="project_search_filter::Filter", tags="1, 2, 3")]
    pub filter: ::core::option::Option<project_search_filter::Filter>,
}
/// Nested message and enum types in `ProjectSearchFilter`.
pub mod project_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for projects with a specific name.
        #[prost(message, tag="1")]
        ProjectNameFilter(super::ProjectNameFilter),
        /// Filter for projects with a specific ID.
        #[prost(message, tag="2")]
        InProjectIdsFilter(super::super::super::filter::v2::InIDsFilter),
        /// Filter for projects that are owned by or granted to a specific organization.
        /// You can specify whether to search for owned, granted or both types of projects.
        #[prost(message, tag="3")]
        OrganizationIdFilter(super::ProjectOrganizationIdFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectNameFilter {
    /// Defines the name of the project to query for.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// Defines which text comparison method used for the name query.
    #[prost(enumeration="super::super::filter::v2::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectOrganizationIdFilter {
    /// OrganizationID Is the ID of the organization to query for.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Defines whether to filter for owned, granted or both types of projects.
    /// If not specified, defaults to OWNED_OR_GRANTED and will return both owned and granted projects.
    #[prost(enumeration="project_organization_id_filter::Type", tag="2")]
    pub r#type: i32,
}
/// Nested message and enum types in `ProjectOrganizationIDFilter`.
pub mod project_organization_id_filter {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        Unspecified = 0,
        /// Filter for projects that are owned by the organization.
        Owned = 1,
        /// Filter for projects that are granted to the organization.
        Granted = 2,
        /// Filter for projects that are either owned by or granted to the organization.
        OwnedOrGranted = 3,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "TYPE_UNSPECIFIED",
                Self::Owned => "OWNED",
                Self::Granted => "GRANTED",
                Self::OwnedOrGranted => "OWNED_OR_GRANTED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "OWNED" => Some(Self::Owned),
                "GRANTED" => Some(Self::Granted),
                "OWNED_OR_GRANTED" => Some(Self::OwnedOrGranted),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectGrantSearchFilter {
    #[prost(oneof="project_grant_search_filter::Filter", tags="1, 2, 3, 4, 5")]
    pub filter: ::core::option::Option<project_grant_search_filter::Filter>,
}
/// Nested message and enum types in `ProjectGrantSearchFilter`.
pub mod project_grant_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for project grants with a specific project name.
        #[prost(message, tag="1")]
        ProjectNameFilter(super::ProjectNameFilter),
        /// Filter for project grants where a specific role is granted.
        #[prost(message, tag="2")]
        RoleKeyFilter(super::ProjectRoleKeyFilter),
        /// Filter for project grants of a specific project ID.
        #[prost(message, tag="3")]
        InProjectIdsFilter(super::super::super::filter::v2::InIDsFilter),
        /// Filter for project grants that were granted from a specific organization.
        #[prost(message, tag="4")]
        OrganizationIdFilter(super::super::super::filter::v2::IdFilter),
        /// Filter for project grants that were granted to a specific organization.
        #[prost(message, tag="5")]
        GrantedOrganizationIdFilter(super::super::super::filter::v2::IdFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRole {
    /// ProjectID is the ID of the project the role belongs to.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Key of the project role. The key identifies the role. It's the only relevant attribute for Zitadel and
    /// will be used for authorization checks and as claim in tokens and user info responses.
    #[prost(string, tag="2")]
    pub key: ::prost::alloc::string::String,
    /// CreationDate is the timestamp of the project role creation.
    #[prost(message, optional, tag="3")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// ChangeDate is the timestamp of the last change to the project role.
    #[prost(message, optional, tag="4")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// DisplayName is a human readable name for the role, which might be displayed to users.
    #[prost(string, tag="5")]
    pub display_name: ::prost::alloc::string::String,
    /// Group allows grouping roles for display purposes. Zitadel will not handle it in any way.
    /// It can be used to group roles in a UI to allow easier management for administrators.
    /// This attribute is not to be confused with groups as a collection of users.
    #[prost(string, tag="6")]
    pub group: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRoleSearchFilter {
    #[prost(oneof="project_role_search_filter::Filter", tags="1, 2")]
    pub filter: ::core::option::Option<project_role_search_filter::Filter>,
}
/// Nested message and enum types in `ProjectRoleSearchFilter`.
pub mod project_role_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for project roles with a specific key.
        #[prost(message, tag="1")]
        RoleKeyFilter(super::ProjectRoleKeyFilter),
        /// Filter for project roles with a specific display name.
        #[prost(message, tag="2")]
        DisplayNameFilter(super::ProjectRoleDisplayNameFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRoleKeyFilter {
    /// The key of the project role to query for.
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    /// Defines which text comparison method used for the key query.
    #[prost(enumeration="super::super::filter::v2::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRoleDisplayNameFilter {
    /// The display name of the project role to query for.
    #[prost(string, tag="1")]
    pub display_name: ::prost::alloc::string::String,
    /// Defines which text comparison method used for the name query.
    #[prost(enumeration="super::super::filter::v2::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectGrantState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
}
impl ProjectGrantState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_GRANT_STATE_UNSPECIFIED",
            Self::Active => "PROJECT_GRANT_STATE_ACTIVE",
            Self::Inactive => "PROJECT_GRANT_STATE_INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_GRANT_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_GRANT_STATE_ACTIVE" => Some(Self::Active),
            "PROJECT_GRANT_STATE_INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
}
impl ProjectState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_STATE_UNSPECIFIED",
            Self::Active => "PROJECT_STATE_ACTIVE",
            Self::Inactive => "PROJECT_STATE_INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_STATE_ACTIVE" => Some(Self::Active),
            "PROJECT_STATE_INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GrantedProjectState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
}
impl GrantedProjectState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "GRANTED_PROJECT_STATE_UNSPECIFIED",
            Self::Active => "GRANTED_PROJECT_STATE_ACTIVE",
            Self::Inactive => "GRANTED_PROJECT_STATE_INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GRANTED_PROJECT_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "GRANTED_PROJECT_STATE_ACTIVE" => Some(Self::Active),
            "GRANTED_PROJECT_STATE_INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PrivateLabelingSetting {
    Unspecified = 0,
    EnforceProjectResourceOwnerPolicy = 1,
    AllowLoginUserResourceOwnerPolicy = 2,
}
impl PrivateLabelingSetting {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRIVATE_LABELING_SETTING_UNSPECIFIED",
            Self::EnforceProjectResourceOwnerPolicy => "PRIVATE_LABELING_SETTING_ENFORCE_PROJECT_RESOURCE_OWNER_POLICY",
            Self::AllowLoginUserResourceOwnerPolicy => "PRIVATE_LABELING_SETTING_ALLOW_LOGIN_USER_RESOURCE_OWNER_POLICY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRIVATE_LABELING_SETTING_UNSPECIFIED" => Some(Self::Unspecified),
            "PRIVATE_LABELING_SETTING_ENFORCE_PROJECT_RESOURCE_OWNER_POLICY" => Some(Self::EnforceProjectResourceOwnerPolicy),
            "PRIVATE_LABELING_SETTING_ALLOW_LOGIN_USER_RESOURCE_OWNER_POLICY" => Some(Self::AllowLoginUserResourceOwnerPolicy),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectFieldName {
    Unspecified = 0,
    Id = 1,
    CreationDate = 2,
    ChangeDate = 3,
    Name = 4,
}
impl ProjectFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_FIELD_NAME_UNSPECIFIED",
            Self::Id => "PROJECT_FIELD_NAME_ID",
            Self::CreationDate => "PROJECT_FIELD_NAME_CREATION_DATE",
            Self::ChangeDate => "PROJECT_FIELD_NAME_CHANGE_DATE",
            Self::Name => "PROJECT_FIELD_NAME_NAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_FIELD_NAME_ID" => Some(Self::Id),
            "PROJECT_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            "PROJECT_FIELD_NAME_CHANGE_DATE" => Some(Self::ChangeDate),
            "PROJECT_FIELD_NAME_NAME" => Some(Self::Name),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectGrantFieldName {
    Unspecified = 0,
    ProjectId = 1,
    CreationDate = 2,
    ChangeDate = 3,
}
impl ProjectGrantFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_GRANT_FIELD_NAME_UNSPECIFIED",
            Self::ProjectId => "PROJECT_GRANT_FIELD_NAME_PROJECT_ID",
            Self::CreationDate => "PROJECT_GRANT_FIELD_NAME_CREATION_DATE",
            Self::ChangeDate => "PROJECT_GRANT_FIELD_NAME_CHANGE_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_GRANT_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_GRANT_FIELD_NAME_PROJECT_ID" => Some(Self::ProjectId),
            "PROJECT_GRANT_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            "PROJECT_GRANT_FIELD_NAME_CHANGE_DATE" => Some(Self::ChangeDate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectRoleFieldName {
    Unspecified = 0,
    Key = 1,
    CreationDate = 2,
    ChangeDate = 3,
}
impl ProjectRoleFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_ROLE_FIELD_NAME_UNSPECIFIED",
            Self::Key => "PROJECT_ROLE_FIELD_NAME_KEY",
            Self::CreationDate => "PROJECT_ROLE_FIELD_NAME_CREATION_DATE",
            Self::ChangeDate => "PROJECT_ROLE_FIELD_NAME_CHANGE_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_ROLE_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_ROLE_FIELD_NAME_KEY" => Some(Self::Key),
            "PROJECT_ROLE_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            "PROJECT_ROLE_FIELD_NAME_CHANGE_DATE" => Some(Self::ChangeDate),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectRequest {
    /// OrganizationID is the unique identifier of the organization the project belongs to.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// ProjectID is the unique identifier of the new project. This field is optional.
    /// If omitted, the system will generate a unique ID for you. This is the
    /// recommended way. The generated ID will be returned in the response.
    #[prost(string, optional, tag="2")]
    pub project_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Name of the project. This might be presented to users, e.g. in sign-in flows.
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    /// ProjectRoleAssertion is a  setting that can be enabled to have role information
    /// included in the user info endpoint.
    /// It is also dependent on your application settings to include it in tokens and other types.
    #[prost(bool, tag="4")]
    pub project_role_assertion: bool,
    /// AuthorizationRequired is a boolean flag that can be enabled to check if a user has
    /// an authorization to use this project assigned when login into an application of this project.
    #[prost(bool, tag="5")]
    pub authorization_required: bool,
    /// ProjectAccessRequired is a boolean flag that can be enabled to check if the organization
    /// of the user, that is trying to log in,
    /// has access to this project (either owns the project or is granted).
    #[prost(bool, tag="6")]
    pub project_access_required: bool,
    /// PrivateLabelingSetting is a setting that defines which private labeling/branding should
    /// trigger when getting to a login of this project.
    #[prost(enumeration="PrivateLabelingSetting", tag="7")]
    pub private_labeling_setting: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectResponse {
    /// ProjectID is the unique identifier of the newly created project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// CreationDate is the timestamp of the project creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectRequest {
    /// ProjectID is the unique identifier of the project to be updated.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Name is used to update the name of the project. This field is optional.
    /// If omitted, the name will remain unchanged.
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// ProjectRoleAssertion is a setting that can be enabled to have role information
    /// included in the user info endpoint.
    /// It is also dependent on your application settings to include it in tokens and other types.
    /// If omitted, the setting will remain unchanged.
    #[prost(bool, optional, tag="3")]
    pub project_role_assertion: ::core::option::Option<bool>,
    /// AuthorizationRequired is a boolean flag that can be enabled to check if a user has
    /// a role of this project assigned when logging into an application of this project.
    /// If omitted, the setting will remain unchanged.
    #[prost(bool, optional, tag="4")]
    pub authorization_required: ::core::option::Option<bool>,
    /// ProjectAccessRequired is a boolean flag that can be enabled to check if the organization
    /// of the user has a grant to this project.
    /// If omitted, the setting will remain unchanged.
    #[prost(bool, optional, tag="5")]
    pub project_access_required: ::core::option::Option<bool>,
    /// PrivateLabelingSetting is a setting that defines which private labeling/branding should
    /// trigger when getting to a login of this project.
    /// If omitted, the setting will remain unchanged.
    #[prost(enumeration="PrivateLabelingSetting", optional, tag="6")]
    pub private_labeling_setting: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectResponse {
    /// ChangeDate is the timestamp of the change of the project.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectRequest {
    /// ProjectID is the unique identifier of the project to be deleted.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectResponse {
    /// DeletionDate is the timestamp of the deletion of the project.
    /// Note that the deletion date is only guaranteed to be set if the deletion was successful during the request.
    /// In case the deletion occurred in a previous request, the deletion date might be empty.
    #[prost(message, optional, tag="3")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectRequest {
    /// ProjectID is the unique identifier of the project to be retrieved.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectResponse {
    /// Project is the project that matches the project ID used in the request.
    #[prost(message, optional, tag="1")]
    pub project: ::core::option::Option<Project>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectsRequest {
    /// Pagination can be used to list limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// SortingColumn is the field the result is sorted by. The default is the creation date.
    /// Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="ProjectFieldName", optional, tag="2")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Filters define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<ProjectSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectsResponse {
    /// Pagination contains the total number of projects matching the query and the applied limit.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// Projects is a list of projects matching the query.
    #[prost(message, repeated, tag="2")]
    pub projects: ::prost::alloc::vec::Vec<Project>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectResponse {
    /// ChangeDate is the timestamp of the change of the project.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectResponse {
    /// ChangeDate is the timestamp of the change of the project.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddProjectRoleRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// RoleKey identifies the role. It's the only relevant attribute for Zitadel and
    /// will be used for authorization checks and as claim in tokens and user info responses.
    #[prost(string, tag="2")]
    pub role_key: ::prost::alloc::string::String,
    /// DisplayName is a human readable name for the role, which might be displayed to users.
    #[prost(string, tag="3")]
    pub display_name: ::prost::alloc::string::String,
    /// Group allows grouping roles for display purposes. Zitadel will not handle it in any way.
    /// It can be used to group roles in a UI to allow easier management for administrators.
    /// This attribute is not to be confused with groups as a collection of users.
    #[prost(string, optional, tag="4")]
    pub group: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddProjectRoleResponse {
    /// CreationDate is the timestamp of the project role creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectRoleRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// RoleKey identifies the role. It's the only relevant attribute for Zitadel and
    /// will be used for authorization checks and as claim in tokens and user info responses.
    /// It cannot be changed. If you need a different key, remove the role and create a new one.
    #[prost(string, tag="2")]
    pub role_key: ::prost::alloc::string::String,
    /// DisplayName is the human readable name for the role, which might be displayed to users.
    /// If omitted, the name will remain unchanged.
    #[prost(string, optional, tag="3")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Group allows grouping roles for display purposes. Zitadel will not handle it in any way.
    /// It can be used to group roles in a UI to allow easier management for administrators.
    /// If omitted, the group will remain unchanged.
    /// This attribute is not to be confused with groups as a collection of users.
    #[prost(string, optional, tag="4")]
    pub group: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectRoleResponse {
    /// ChangeDate is the timestamp of the change of the project role.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveProjectRoleRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// RoleKey is the key of the role to be removed.
    /// All dependencies of this role will be removed as well, including project grants and user grants (role assignments).
    /// If the role is not found, the request will return a successful response as the desired state is already achieved.
    #[prost(string, tag="2")]
    pub role_key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveProjectRoleResponse {
    /// RemovalDate is the timestamp of the removal of the project role.
    /// Note that the removal date is only guaranteed to be set if the removal was successful during the request.
    /// In case the removal occurred in a previous request, the removal date might be empty.
    #[prost(message, optional, tag="3")]
    pub removal_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectRolesRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Pagination can be used to list limitations and ordering.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// SortingColumn is the field the result is sorted by. The default is the creation date.
    /// Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="ProjectRoleFieldName", optional, tag="3")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Filters define the criteria to query for.
    #[prost(message, repeated, tag="4")]
    pub filters: ::prost::alloc::vec::Vec<ProjectRoleSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectRolesResponse {
    /// Pagination contains the total number of project roles matching the query and the applied limit.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// ProjectRoles is a list of roles matching the query.
    #[prost(message, repeated, tag="2")]
    pub project_roles: ::prost::alloc::vec::Vec<ProjectRole>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectGrantRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// GrantedOrganizationID is the unique identifier of the organization the project will be granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
    /// RoleKeys is a list of roles to be granted to the organization for self management.
    /// The roles are identified by their keys.
    #[prost(string, repeated, tag="3")]
    pub role_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectGrantResponse {
    /// CreationDate is the timestamp of the project grant creation.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectGrantRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// GrantedOrganizationID is the unique identifier of the organization the project was granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
    /// RoleKeys is a list of roles to be granted to the organization for self management.
    /// The roles are identified by their keys.
    /// Any roles not included in this list will be removed from the project grant.
    /// If you want to add a role, make sure to include all other existing roles as well.
    /// If any previous role is removed, all user grants (role assignments) for this project grant with this role will be removed as well.
    #[prost(string, repeated, tag="3")]
    pub role_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectGrantResponse {
    /// ChangeDate is the timestamp of the change of the project grant.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectGrantRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// GrantedOrganizationID is the unique identifier of the organization the project was granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectGrantResponse {
    /// DeletionDate is the timestamp of the deletion of the project grant.
    /// Note that the deletion date is only guaranteed to be set if the deletion was successful during the request.
    /// In case the deletion occurred in a previous request, the deletion date might be empty.
    #[prost(message, optional, tag="3")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectGrantRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// GrantedOrganizationID is the unique identifier of the organization the project was granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectGrantResponse {
    /// ChangeDate is the timestamp of the change of the project grant.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectGrantRequest {
    /// ProjectID is the unique identifier of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// GrantedOrganizationID is the unique identifier of the organization the project was granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectGrantResponse {
    /// ChangeDate is the timestamp of the change of the project grant.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectGrantsRequest {
    /// Pagination can be used to list limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// SortingColumn is the field the result is sorted by. The default is the creation date.
    /// Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="ProjectGrantFieldName", optional, tag="2")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Filters define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<ProjectGrantSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectGrantsResponse {
    /// Pagination contains the total number of project grants matching the query and the applied limit.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// ProjectGrants is a list of project grants matching the query.
    #[prost(message, repeated, tag="2")]
    pub project_grants: ::prost::alloc::vec::Vec<ProjectGrant>,
}
include!("zitadel.project.v2.tonic.rs");
// @@protoc_insertion_point(module)