// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectGrant {
    /// The unique identifier of the organization which granted the project to the granted_organization_id.
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    /// The timestamp of the granted project creation.
    #[prost(message, optional, tag="3")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The timestamp of the last change to the granted project (e.g. creation, activation, deactivation).
    #[prost(message, optional, tag="4")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The ID of the organization the project is granted to.
    #[prost(string, tag="5")]
    pub granted_organization_id: ::prost::alloc::string::String,
    /// The name of the organization the project is granted to.
    #[prost(string, tag="6")]
    pub granted_organization_name: ::prost::alloc::string::String,
    /// The roles of the granted project.
    #[prost(string, repeated, tag="7")]
    pub granted_role_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The ID of the granted project.
    #[prost(string, tag="8")]
    pub project_id: ::prost::alloc::string::String,
    /// The name of the granted project.
    #[prost(string, tag="9")]
    pub project_name: ::prost::alloc::string::String,
    /// Describes the current state of the granted project.
    #[prost(enumeration="ProjectGrantState", tag="10")]
    pub state: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Project {
    /// The unique identifier of the project.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// The unique identifier of the organization the project belongs to.
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    /// The timestamp of the project creation.
    #[prost(message, optional, tag="3")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The timestamp of the last change to the project (e.g. creation, activation, deactivation).
    #[prost(message, optional, tag="4")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The name of the project.
    #[prost(string, tag="5")]
    pub name: ::prost::alloc::string::String,
    /// Describes the current state of the project.
    #[prost(enumeration="ProjectState", tag="6")]
    pub state: i32,
    /// Describes if the roles of the user should be added to the token.
    #[prost(bool, tag="7")]
    pub project_role_assertion: bool,
    /// When enabled, ZITADEL will check if a user has appropriate role assignments to use this project when they log into an application of this project.
    #[prost(bool, tag="8")]
    pub authorization_required: bool,
    /// When enabled, ZITADEL will check if the organization of the user, that is trying to log in, has access to this project (either owns the project or is granted).
    #[prost(bool, tag="9")]
    pub project_access_required: bool,
    /// Defines from where the private labeling should be triggered.
    #[prost(enumeration="PrivateLabelingSetting", tag="10")]
    pub private_labeling_setting: i32,
    /// The ID of the organization the project is granted to.
    #[prost(string, optional, tag="12")]
    pub granted_organization_id: ::core::option::Option<::prost::alloc::string::String>,
    /// The name of the organization the project is granted to.
    #[prost(string, optional, tag="13")]
    pub granted_organization_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Describes the current state of the granted project.
    #[prost(enumeration="GrantedProjectState", tag="14")]
    pub granted_state: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectSearchFilter {
    #[prost(oneof="project_search_filter::Filter", tags="1, 2, 3, 4, 5")]
    pub filter: ::core::option::Option<project_search_filter::Filter>,
}
/// Nested message and enum types in `ProjectSearchFilter`.
pub mod project_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        #[prost(message, tag="1")]
        ProjectNameFilter(super::ProjectNameFilter),
        #[prost(message, tag="2")]
        InProjectIdsFilter(super::super::super::filter::v2beta::InIDsFilter),
        #[prost(message, tag="3")]
        ProjectResourceOwnerFilter(super::super::super::filter::v2beta::IdFilter),
        #[prost(message, tag="4")]
        ProjectGrantResourceOwnerFilter(super::super::super::filter::v2beta::IdFilter),
        #[prost(message, tag="5")]
        ProjectOrganizationIdFilter(super::super::super::filter::v2beta::IdFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectNameFilter {
    /// Defines the name of the project to query for.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// Defines which text comparison method used for the name query.
    #[prost(enumeration="super::super::filter::v2beta::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectGrantSearchFilter {
    #[prost(oneof="project_grant_search_filter::Filter", tags="1, 2, 3, 4, 5")]
    pub filter: ::core::option::Option<project_grant_search_filter::Filter>,
}
/// Nested message and enum types in `ProjectGrantSearchFilter`.
pub mod project_grant_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        #[prost(message, tag="1")]
        ProjectNameFilter(super::ProjectNameFilter),
        #[prost(message, tag="2")]
        RoleKeyFilter(super::ProjectRoleKeyFilter),
        #[prost(message, tag="3")]
        InProjectIdsFilter(super::super::super::filter::v2beta::InIDsFilter),
        #[prost(message, tag="4")]
        ProjectResourceOwnerFilter(super::super::super::filter::v2beta::IdFilter),
        #[prost(message, tag="5")]
        ProjectGrantResourceOwnerFilter(super::super::super::filter::v2beta::IdFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRole {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Key of the project role.
    #[prost(string, tag="2")]
    pub key: ::prost::alloc::string::String,
    /// The timestamp of the project role creation.
    #[prost(message, optional, tag="3")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The timestamp of the last change to the project role.
    #[prost(message, optional, tag="4")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Display name of the project role.
    #[prost(string, tag="5")]
    pub display_name: ::prost::alloc::string::String,
    /// Group of the project role.
    #[prost(string, tag="6")]
    pub group: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRoleSearchFilter {
    #[prost(oneof="project_role_search_filter::Filter", tags="1, 2")]
    pub filter: ::core::option::Option<project_role_search_filter::Filter>,
}
/// Nested message and enum types in `ProjectRoleSearchFilter`.
pub mod project_role_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        #[prost(message, tag="1")]
        RoleKeyFilter(super::ProjectRoleKeyFilter),
        #[prost(message, tag="2")]
        DisplayNameFilter(super::ProjectRoleDisplayNameFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRoleKeyFilter {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    /// Defines which text comparison method used for the name query.
    #[prost(enumeration="super::super::filter::v2beta::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRoleDisplayNameFilter {
    #[prost(string, tag="1")]
    pub display_name: ::prost::alloc::string::String,
    /// Defines which text comparison method used for the name query.
    #[prost(enumeration="super::super::filter::v2beta::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectGrantState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
}
impl ProjectGrantState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_GRANT_STATE_UNSPECIFIED",
            Self::Active => "PROJECT_GRANT_STATE_ACTIVE",
            Self::Inactive => "PROJECT_GRANT_STATE_INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_GRANT_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_GRANT_STATE_ACTIVE" => Some(Self::Active),
            "PROJECT_GRANT_STATE_INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
}
impl ProjectState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_STATE_UNSPECIFIED",
            Self::Active => "PROJECT_STATE_ACTIVE",
            Self::Inactive => "PROJECT_STATE_INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_STATE_ACTIVE" => Some(Self::Active),
            "PROJECT_STATE_INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GrantedProjectState {
    Unspecified = 0,
    Active = 1,
    Inactive = 2,
}
impl GrantedProjectState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "GRANTED_PROJECT_STATE_UNSPECIFIED",
            Self::Active => "GRANTED_PROJECT_STATE_ACTIVE",
            Self::Inactive => "GRANTED_PROJECT_STATE_INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GRANTED_PROJECT_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "GRANTED_PROJECT_STATE_ACTIVE" => Some(Self::Active),
            "GRANTED_PROJECT_STATE_INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PrivateLabelingSetting {
    Unspecified = 0,
    EnforceProjectResourceOwnerPolicy = 1,
    AllowLoginUserResourceOwnerPolicy = 2,
}
impl PrivateLabelingSetting {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRIVATE_LABELING_SETTING_UNSPECIFIED",
            Self::EnforceProjectResourceOwnerPolicy => "PRIVATE_LABELING_SETTING_ENFORCE_PROJECT_RESOURCE_OWNER_POLICY",
            Self::AllowLoginUserResourceOwnerPolicy => "PRIVATE_LABELING_SETTING_ALLOW_LOGIN_USER_RESOURCE_OWNER_POLICY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRIVATE_LABELING_SETTING_UNSPECIFIED" => Some(Self::Unspecified),
            "PRIVATE_LABELING_SETTING_ENFORCE_PROJECT_RESOURCE_OWNER_POLICY" => Some(Self::EnforceProjectResourceOwnerPolicy),
            "PRIVATE_LABELING_SETTING_ALLOW_LOGIN_USER_RESOURCE_OWNER_POLICY" => Some(Self::AllowLoginUserResourceOwnerPolicy),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectFieldName {
    Unspecified = 0,
    Id = 1,
    CreationDate = 2,
    ChangeDate = 3,
    Name = 4,
}
impl ProjectFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_FIELD_NAME_UNSPECIFIED",
            Self::Id => "PROJECT_FIELD_NAME_ID",
            Self::CreationDate => "PROJECT_FIELD_NAME_CREATION_DATE",
            Self::ChangeDate => "PROJECT_FIELD_NAME_CHANGE_DATE",
            Self::Name => "PROJECT_FIELD_NAME_NAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_FIELD_NAME_ID" => Some(Self::Id),
            "PROJECT_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            "PROJECT_FIELD_NAME_CHANGE_DATE" => Some(Self::ChangeDate),
            "PROJECT_FIELD_NAME_NAME" => Some(Self::Name),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectGrantFieldName {
    Unspecified = 0,
    ProjectId = 1,
    CreationDate = 2,
    ChangeDate = 3,
}
impl ProjectGrantFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_GRANT_FIELD_NAME_UNSPECIFIED",
            Self::ProjectId => "PROJECT_GRANT_FIELD_NAME_PROJECT_ID",
            Self::CreationDate => "PROJECT_GRANT_FIELD_NAME_CREATION_DATE",
            Self::ChangeDate => "PROJECT_GRANT_FIELD_NAME_CHANGE_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_GRANT_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_GRANT_FIELD_NAME_PROJECT_ID" => Some(Self::ProjectId),
            "PROJECT_GRANT_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            "PROJECT_GRANT_FIELD_NAME_CHANGE_DATE" => Some(Self::ChangeDate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProjectRoleFieldName {
    Unspecified = 0,
    Key = 1,
    CreationDate = 2,
    ChangeDate = 3,
}
impl ProjectRoleFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROJECT_ROLE_FIELD_NAME_UNSPECIFIED",
            Self::Key => "PROJECT_ROLE_FIELD_NAME_KEY",
            Self::CreationDate => "PROJECT_ROLE_FIELD_NAME_CREATION_DATE",
            Self::ChangeDate => "PROJECT_ROLE_FIELD_NAME_CHANGE_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROJECT_ROLE_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "PROJECT_ROLE_FIELD_NAME_KEY" => Some(Self::Key),
            "PROJECT_ROLE_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            "PROJECT_ROLE_FIELD_NAME_CHANGE_DATE" => Some(Self::ChangeDate),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProjectRequest {
    /// The unique identifier of the organization the project belongs to.
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    /// The unique identifier of the project.
    #[prost(string, optional, tag="2")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
    /// Name of the project.
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    /// Enable this setting to provide role information to your application. For OpenID Connect, the roles can be requested from the UserInfo endpoint or sent in the ID or Access Token, based on your application's configuration.
    #[prost(bool, tag="4")]
    pub project_role_assertion: bool,
    /// Deny authentication if the user has no authorization assigned to this project. Authorizations to the project without assigned a specific role to the user are allowed.
    #[prost(bool, tag="5")]
    pub authorization_required: bool,
    /// Before a user can be authenticated, it is verified that their affiliated organization has been granted access to this project. Authentication is not permitted for users from unauthorized organizations.
    #[prost(bool, tag="6")]
    pub project_access_required: bool,
    /// Define which private labeling/branding should trigger when getting to a login of this project.
    #[prost(enumeration="PrivateLabelingSetting", tag="7")]
    pub private_labeling_setting: i32,
    /// List of users and Project Member roles (PROJECT_OWNER, by default) to be assigned to those users.
    #[prost(message, repeated, tag="8")]
    pub admins: ::prost::alloc::vec::Vec<create_project_request::Admin>,
}
/// Nested message and enum types in `CreateProjectRequest`.
pub mod create_project_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Admin {
        #[prost(string, tag="1")]
        pub user_id: ::prost::alloc::string::String,
        /// specify the Project Member Roles for the provided user (default is PROJECT_OWNER if roles are empty
        #[prost(string, repeated, tag="3")]
        pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectResponse {
    /// The unique identifier of the newly created project.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// The timestamp of the project creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Name of the project.
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// Enable this setting to have role information included in the user info endpoint. It is also dependent on your application settings to include it in tokens and other types.
    #[prost(bool, optional, tag="3")]
    pub project_role_assertion: ::core::option::Option<bool>,
    /// When enabled Zitadel will check if a user has a role of this project assigned when login into an application of this project.
    #[prost(bool, optional, tag="4")]
    pub project_role_check: ::core::option::Option<bool>,
    /// When enabled Zitadel will check if the organization of the user, that is trying to log in, has a grant to this project.
    #[prost(bool, optional, tag="5")]
    pub has_project_check: ::core::option::Option<bool>,
    /// Define which private labeling/branding should trigger when getting to a login of this project.
    #[prost(enumeration="PrivateLabelingSetting", optional, tag="6")]
    pub private_labeling_setting: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectResponse {
    /// The timestamp of the change of the project.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectRequest {
    /// The unique identifier of the project.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectResponse {
    /// The timestamp of the deletion of the project.
    /// Note that the deletion date is only guaranteed to be set if the deletion was successful during the request.
    /// In case the deletion occurred in a previous request, the deletion date might be empty.
    #[prost(message, optional, tag="3")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectRequest {
    /// The unique identifier of the project.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectResponse {
    #[prost(message, optional, tag="1")]
    pub project: ::core::option::Option<Project>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectsRequest {
    /// List limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationRequest>,
    /// The field the result is sorted by. The default is the creation date. Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="ProjectFieldName", optional, tag="2")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<ProjectSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectsResponse {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationResponse>,
    #[prost(message, repeated, tag="2")]
    pub projects: ::prost::alloc::vec::Vec<Project>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectRequest {
    /// The unique identifier of the project.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectResponse {
    /// The timestamp of the change of the project.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectRequest {
    /// The unique identifier of the project.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectResponse {
    /// The timestamp of the change of the project.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddProjectRoleRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// The key is the only relevant attribute for Zitadel regarding the authorization checks.
    #[prost(string, tag="2")]
    pub role_key: ::prost::alloc::string::String,
    /// Name displayed for the role.
    #[prost(string, tag="3")]
    pub display_name: ::prost::alloc::string::String,
    /// The group is only used for display purposes. That you have better handling, like giving all the roles from a group to a user.
    #[prost(string, optional, tag="4")]
    pub group: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddProjectRoleResponse {
    /// The timestamp of the project role creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectRoleRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// The key is the only relevant attribute for Zitadel regarding the authorization checks.
    #[prost(string, tag="2")]
    pub role_key: ::prost::alloc::string::String,
    /// Name displayed for the role.
    #[prost(string, optional, tag="3")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    /// The group is only used for display purposes. That you have better handling, like giving all the roles from a group to a user.
    #[prost(string, optional, tag="4")]
    pub group: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectRoleResponse {
    /// The timestamp of the change of the project role.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveProjectRoleRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// The key is the only relevant attribute for Zitadel regarding the authorization checks.
    #[prost(string, tag="2")]
    pub role_key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveProjectRoleResponse {
    /// The timestamp of the removal of the project role.
    /// Note that the removal date is only guaranteed to be set if the removal was successful during the request.
    /// In case the removal occurred in a previous request, the removal date might be empty.
    #[prost(message, optional, tag="3")]
    pub removal_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectRolesRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// List limitations and ordering.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationRequest>,
    /// The field the result is sorted by. The default is the creation date. Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="ProjectRoleFieldName", optional, tag="3")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="4")]
    pub filters: ::prost::alloc::vec::Vec<ProjectRoleSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectRolesResponse {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationResponse>,
    #[prost(message, repeated, tag="2")]
    pub project_roles: ::prost::alloc::vec::Vec<ProjectRole>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectGrantRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Organization the project is granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
    /// Keys of the role available for the project grant.
    #[prost(string, repeated, tag="3")]
    pub role_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectGrantResponse {
    /// The timestamp of the project grant creation.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectGrantRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Organization the project is granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
    /// Keys of the role available for the project grant.
    #[prost(string, repeated, tag="3")]
    pub role_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProjectGrantResponse {
    /// The timestamp of the change of the project grant.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectGrantRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Organization the project is granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProjectGrantResponse {
    /// The timestamp of the deletion of the project grant.
    /// Note that the deletion date is only guaranteed to be set if the deletion was successful during the request.
    /// In case the deletion occurred in a previous request, the deletion date might be empty.
    #[prost(message, optional, tag="3")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectGrantRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Organization the project is granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivateProjectGrantResponse {
    /// The timestamp of the change of the project grant.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectGrantRequest {
    /// ID of the project.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
    /// Organization the project is granted to.
    #[prost(string, tag="2")]
    pub granted_organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateProjectGrantResponse {
    /// The timestamp of the change of the project grant.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectGrantsRequest {
    /// List limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationRequest>,
    /// The field the result is sorted by. The default is the creation date. Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="ProjectGrantFieldName", optional, tag="2")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<ProjectGrantSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProjectGrantsResponse {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2beta::PaginationResponse>,
    #[prost(message, repeated, tag="2")]
    pub project_grants: ::prost::alloc::vec::Vec<ProjectGrant>,
}
include!("zitadel.project.v2beta.tonic.rs");
// @@protoc_insertion_point(module)