// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestChallenges {
    /// WebAuthN requests a challenge to be used in the WebAuthN authentication ceremony.
    /// They can be used for both passkey and U2F authentication.
    /// They're required for a webauthn check at the SetSession endpoint.
    #[prost(message, optional, tag="1")]
    pub web_auth_n: ::core::option::Option<request_challenges::WebAuthN>,
    /// OTPSMS requests a code to be sent via SMS to the user's primary phone.
    /// It is required for an OTP check at the SetSession endpoint.
    #[prost(message, optional, tag="2")]
    pub otp_sms: ::core::option::Option<request_challenges::Otpsms>,
    /// OTPEmail requests a code to be sent via email to the user's primary email address.
    /// It is required for an OTP check at the SetSession endpoint.
    #[prost(message, optional, tag="3")]
    pub otp_email: ::core::option::Option<request_challenges::OtpEmail>,
}
/// Nested message and enum types in `RequestChallenges`.
pub mod request_challenges {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct WebAuthN {
        /// The domain on which the session was created. Will be used in the WebAuthN challenge.
        /// It must be either the exact domain or a top-level domain of the origin of the request.
        /// For example if the request is coming from "login.example.com", the domain can be
        /// "login.example.com" or "example.com", but not "other.com" or "sub.login.example.com".
        /// See also: <https://www.w3.org/TR/webauthn/#relying-party-identifier>
        #[prost(string, tag="1")]
        pub domain: ::prost::alloc::string::String,
        /// User verification that is required during validation.
        /// When set to `USER_VERIFICATION_REQUIREMENT_REQUIRED` the behaviour is for passkey authentication.
        /// Other values will mean U2F.
        /// See also: <https://www.w3.org/TR/webauthn/#enum-userVerificationRequirement>
        /// If either the value is set to USER_VERIFICATION_REQUIREMENT_REQUIRED or the user verification
        /// is passed as part of the authentication ceremony, the user_verified flag will be set in the resulting webauthn factor.
        #[prost(enumeration="super::UserVerificationRequirement", tag="2")]
        pub user_verification_requirement: i32,
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Otpsms {
        /// Request the code to be returned instead of sending an SMS.
        /// This is useful for testing or in case you want to send the code yourself.
        #[prost(bool, tag="1")]
        pub return_code: bool,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct OtpEmail {
        /// if no delivery_type is specified, an email is sent with the default url
        #[prost(oneof="otp_email::DeliveryType", tags="2, 3")]
        pub delivery_type: ::core::option::Option<otp_email::DeliveryType>,
    }
    /// Nested message and enum types in `OTPEmail`.
    pub mod otp_email {
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct SendCode {
            /// Optionally set a url_template, which will be used in the mail sent by Zitadel to guide the user to your verification page.
            /// If no template is set, the default Zitadel url will be used.
            ///
            /// The following placeholders can be used: Code, UserID, LoginName, DisplayName, PreferredLanguage, SessionID
            #[prost(string, optional, tag="1")]
            pub url_template: ::core::option::Option<::prost::alloc::string::String>,
        }
        #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct ReturnCode {
        }
        /// if no delivery_type is specified, an email is sent with the default url
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
        pub enum DeliveryType {
            #[prost(message, tag="2")]
            SendCode(SendCode),
            #[prost(message, tag="3")]
            ReturnCode(ReturnCode),
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Challenges {
    #[prost(message, optional, tag="1")]
    pub web_auth_n: ::core::option::Option<challenges::WebAuthN>,
    #[prost(string, optional, tag="2")]
    pub otp_sms: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub otp_email: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `Challenges`.
pub mod challenges {
    /// WebAuthN contains the options for the Assertion Generation (dictionary PublicKeyCredentialRequestOptions).
    /// Generated helper methods transform the field to JSON, for use in a WebauthN client.
    /// See also: <https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialrequestoptions>
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct WebAuthN {
        #[prost(message, optional, tag="1")]
        pub public_key_credential_request_options: ::core::option::Option<::pbjson_types::Struct>,
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserVerificationRequirement {
    Unspecified = 0,
    Required = 1,
    Preferred = 2,
    Discouraged = 3,
}
impl UserVerificationRequirement {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "USER_VERIFICATION_REQUIREMENT_UNSPECIFIED",
            Self::Required => "USER_VERIFICATION_REQUIREMENT_REQUIRED",
            Self::Preferred => "USER_VERIFICATION_REQUIREMENT_PREFERRED",
            Self::Discouraged => "USER_VERIFICATION_REQUIREMENT_DISCOURAGED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_VERIFICATION_REQUIREMENT_UNSPECIFIED" => Some(Self::Unspecified),
            "USER_VERIFICATION_REQUIREMENT_REQUIRED" => Some(Self::Required),
            "USER_VERIFICATION_REQUIREMENT_PREFERRED" => Some(Self::Preferred),
            "USER_VERIFICATION_REQUIREMENT_DISCOURAGED" => Some(Self::Discouraged),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    /// Unique identifier of the session.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// The timestamp the session was created.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The timestamp the session was last updated.
    #[prost(message, optional, tag="3")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The sequence of the session represents the change sequence of the session.
    #[prost(uint64, tag="4")]
    pub sequence: u64,
    /// The factors that have been checked for this session, e.g. the user, password and more.
    /// If a factor is set, it means it has been checked and is valid.
    /// If a factor is not set, it means it has not been checked or is invalid.
    /// If a factor is set, the verified_at timestamp indicates when it was last checked.
    #[prost(message, optional, tag="5")]
    pub factors: ::core::option::Option<Factors>,
    /// Metadata contains custom key value pairs set by the user.
    /// The metadata is not interpreted by Zitadel and can be used to store any information
    /// relevant to the session.
    #[prost(map="string, bytes", tag="6")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::vec::Vec<u8>>,
    /// UserAgent contains information about the user agent used to create the session.
    /// This can include information such as the IP address, browser type, and operating system and
    /// a fingerprint id.
    /// This can be used to identify and filter sessions based on the user agent.
    #[prost(message, optional, tag="7")]
    pub user_agent: ::core::option::Option<UserAgent>,
    /// ExpirationDate is the time the session will be automatically invalidated.
    /// If not set, the session does not expire automatically.
    #[prost(message, optional, tag="8")]
    pub expiration_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Factors {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<UserFactor>,
    #[prost(message, optional, tag="2")]
    pub password: ::core::option::Option<PasswordFactor>,
    #[prost(message, optional, tag="3")]
    pub web_auth_n: ::core::option::Option<WebAuthNFactor>,
    #[prost(message, optional, tag="4")]
    pub intent: ::core::option::Option<IntentFactor>,
    #[prost(message, optional, tag="5")]
    pub totp: ::core::option::Option<TotpFactor>,
    #[prost(message, optional, tag="6")]
    pub otp_sms: ::core::option::Option<OtpFactor>,
    #[prost(message, optional, tag="7")]
    pub otp_email: ::core::option::Option<OtpFactor>,
    #[prost(message, optional, tag="8")]
    pub recovery_code: ::core::option::Option<RecoveryCodeFactor>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserFactor {
    /// The timestamp when the user was last verified.
    #[prost(message, optional, tag="1")]
    pub verified_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The unique identifier of the user that was verified.
    #[prost(string, tag="2")]
    pub id: ::prost::alloc::string::String,
    /// The login name of the user that was verified.
    #[prost(string, tag="3")]
    pub login_name: ::prost::alloc::string::String,
    /// The display name of the user that was verified.
    #[prost(string, tag="4")]
    pub display_name: ::prost::alloc::string::String,
    /// The id of the organization the user belongs to.
    #[prost(string, tag="6")]
    pub organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PasswordFactor {
    /// The timestamp when the password was last verified.
    #[prost(message, optional, tag="1")]
    pub verified_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntentFactor {
    /// The timestamp when the intent was last verified.
    #[prost(message, optional, tag="1")]
    pub verified_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WebAuthNFactor {
    /// The timestamp when the passkey challenge was last verified.
    #[prost(message, optional, tag="1")]
    pub verified_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Indicates if the user presence was verified during the last challenge.
    /// This can be used to determine if the factor can be considered as multi-factor authentication.
    #[prost(bool, tag="2")]
    pub user_verified: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TotpFactor {
    /// The timestamp when the TOTP was last verified.
    #[prost(message, optional, tag="1")]
    pub verified_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtpFactor {
    /// The timestamp when the OTP was last verified either by SMS or Email.
    #[prost(message, optional, tag="1")]
    pub verified_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecoveryCodeFactor {
    /// The timestamp when the Recovery Code was last verified.
    #[prost(message, optional, tag="1")]
    pub verified_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchQuery {
    #[prost(oneof="search_query::Query", tags="1, 2, 3, 4, 5, 6")]
    pub query: ::core::option::Option<search_query::Query>,
}
/// Nested message and enum types in `SearchQuery`.
pub mod search_query {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        /// Search for sessions with the given IDs.
        #[prost(message, tag="1")]
        IdsQuery(super::IDsQuery),
        /// Search for sessions of the given user ID.
        #[prost(message, tag="2")]
        UserIdQuery(super::UserIdQuery),
        /// Search for sessions based on their creation date.
        /// This can be used to find sessions created before or after a certain date.
        #[prost(message, tag="3")]
        CreationDateQuery(super::CreationDateQuery),
        /// Search for sessions created by a specific user.
        #[prost(message, tag="4")]
        CreatorQuery(super::CreatorQuery),
        /// Search for sessions based on the user agent used to create the session.
        /// It can be used to find sessions created from a specific device or browser.
        /// This is typically done for providing a list of active sessions to the user
        /// in a user interface.
        #[prost(message, tag="5")]
        UserAgentQuery(super::UserAgentQuery),
        /// Search for sessions based on their expiration date.
        /// This can be used to find sessions that are set to expire before or after a certain date.
        #[prost(message, tag="6")]
        ExpirationDateQuery(super::ExpirationDateQuery),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IDsQuery {
    /// List of session IDs to search for.
    /// If multiple IDs are provided, sessions matching any of the IDs will be returned.
    #[prost(string, repeated, tag="1")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserIdQuery {
    /// ID of the user whose sessions are being searched for.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreationDateQuery {
    /// The creation date to compare the session's creation date against.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The method of comparison to use for the creation date.
    /// This defines whether to search for sessions created before, after, or exactly at the specified date.
    #[prost(enumeration="super::super::v1::TimestampQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreatorQuery {
    /// ID of the user who created the session. If empty, the calling user's ID is used.
    #[prost(string, optional, tag="1")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserAgentQuery {
    /// Finger print id of the user agent used for the session.
    /// Set an empty fingerprint_id to use the user agent from the call.
    /// If the user agent is not available from the current token, an error will be returned.
    #[prost(string, optional, tag="1")]
    pub fingerprint_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExpirationDateQuery {
    /// The expiration date to compare the session's expiration date against.
    #[prost(message, optional, tag="1")]
    pub expiration_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The method of comparison to use for the expiration date.
    /// This defines whether to search for sessions expiring before, after, or exactly at the specified date.
    #[prost(enumeration="super::super::v1::TimestampQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserAgent {
    /// FingerprintID is a unique identifier for the user agent's fingerprint.
    /// It can be used to group sessions by device or browser.
    #[prost(string, optional, tag="1")]
    pub fingerprint_id: ::core::option::Option<::prost::alloc::string::String>,
    /// IP is the IP address from which the session was created.
    #[prost(string, optional, tag="2")]
    pub ip: ::core::option::Option<::prost::alloc::string::String>,
    /// Description is a human-readable description of the user agent.
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map="string, message", tag="4")]
    pub header: ::std::collections::HashMap<::prost::alloc::string::String, user_agent::HeaderValues>,
}
/// Nested message and enum types in `UserAgent`.
pub mod user_agent {
    /// A header may have multiple values.
    /// In Go, headers are defined
    /// as map[string][]string, but protobuf
    /// doesn't allow this scheme.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct HeaderValues {
        #[prost(string, repeated, tag="1")]
        pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SessionFieldName {
    Unspecified = 0,
    CreationDate = 1,
}
impl SessionFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SESSION_FIELD_NAME_UNSPECIFIED",
            Self::CreationDate => "SESSION_FIELD_NAME_CREATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SESSION_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "SESSION_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSessionsRequest {
    /// List limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub query: ::core::option::Option<super::super::object::v2::ListQuery>,
    /// The criteria to be used when searching for sessions.
    /// Multiple queries will be combined with a logical AND.
    #[prost(message, repeated, tag="2")]
    pub queries: ::prost::alloc::vec::Vec<SearchQuery>,
    /// The column to be used for sorting the sessions.
    #[prost(enumeration="SessionFieldName", tag="3")]
    pub sorting_column: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSessionsResponse {
    /// Contains details about the response, such as the total number of sessions.
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::ListDetails>,
    /// The sessions matching the search query. There might be more sessions available
    /// than returned in this response. Use the details field to see if there are more sessions
    /// available and to get the total count of sessions matching the query.
    #[prost(message, repeated, tag="2")]
    pub sessions: ::prost::alloc::vec::Vec<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSessionRequest {
    /// The unique identifier of the session to be retrieved.
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    /// The current token of the session, previously returned on the create / update request.
    /// The token is required unless either of the following conditions is met:
    /// - the caller created the session
    /// - the authenticated user requests their own session (checked user)
    /// - the security token provided in the authorization header has the same user agent as the session
    /// - the caller is granted the permission session.read permission on either the instance or on the checked user's organization
    #[prost(string, optional, tag="2")]
    pub session_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<Session>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSessionRequest {
    /// The checks to be performed during session creation.
    /// Note that a user check can only be performed once per session and cannot be changed afterwards.
    /// Some checks require that the user is already checked, either in the previous or the same
    /// request. For example, a password check requires that the user is already checked.
    /// Other checks, like WebAuthN or IDP intent, require that the user is already checked and a challenge
    /// was requested in any previous request.
    /// On successful checks, the session's `factors` field will be updated.
    #[prost(message, optional, tag="1")]
    pub checks: ::core::option::Option<Checks>,
    /// Custom key value list to be stored on the session.
    #[prost(map="string, bytes", tag="2")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::vec::Vec<u8>>,
    /// Challenges to be requested for further verification.
    /// The challenges will be created and returned in the response.
    /// The challenges can then be used for further checks with the following SetSession method.
    #[prost(message, optional, tag="3")]
    pub challenges: ::core::option::Option<RequestChallenges>,
    /// Store information about the user agent of the client.
    /// This information is stored on the session and can be used for auditing or security purposes.
    /// Sessions can also be filtered by user agent information.
    #[prost(message, optional, tag="4")]
    pub user_agent: ::core::option::Option<UserAgent>,
    /// Duration after which the session will be automatically invalidated.
    /// If not set, the session will not expire automatically and must be deleted manually.
    /// Note that an expired session cannot be used for authentication anymore, but will still be listed
    /// until it is deleted.
    #[prost(message, optional, tag="5")]
    pub lifetime: ::core::option::Option<::pbjson_types::Duration>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSessionResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    /// Unique identifier of the session.
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    /// The current token of the session, which is required for using the session as authentication,
    /// e.g.when authenticating an OIDC auth request or SAML request.
    /// Additionally, the session token can be used as OAuth2 access token to authenticate against
    /// the Zitadel APIs.
    #[prost(string, tag="3")]
    pub session_token: ::prost::alloc::string::String,
    /// The challenges that were requested for the session.
    /// The challenges can be used for further checks with the SetSession method.
    #[prost(message, optional, tag="4")]
    pub challenges: ::core::option::Option<Challenges>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetSessionRequest {
    /// The unique identifier of the session to be updated.
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    /// Deprecated: the session token is no longer required when updating a session
    /// and will be ignored when provided.
    #[deprecated]
    #[prost(string, tag="2")]
    pub session_token: ::prost::alloc::string::String,
    /// Additional checks to be performed on the session.
    /// Successful checks will be stated as factors on the session.
    /// Re-executing a check that was already successful will overwrite the previous check time.
    /// For example, if a password check was already successful, it can be re-checked to update the check time.
    /// Note that a user check can only be performed once per session and cannot be changed afterwards.
    /// Some checks require that the user is already checked, either in the previous or the same request.
    /// For example, a password check requires that the user is already checked.
    /// Other checks, like WebAuthN or IDP intent, require that the user is already checked and a challenge
    /// was requested in any previous request.
    /// On successful checks, the session's `factors` field will be updated.
    #[prost(message, optional, tag="3")]
    pub checks: ::core::option::Option<Checks>,
    /// Additional custom key value pairs to be stored on the session.
    /// Existing keys will be overwritten. To delete a key, set its value to an empty byte array.
    /// Note that metadata keys cannot be changed once the session has been created.
    /// You need to create a new entry and delete the old one instead.
    #[prost(map="string, bytes", tag="4")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::vec::Vec<u8>>,
    /// Additional challenges to be requested for further verification.
    /// The challenges will be created and returned in the response.
    /// The challenges can then be used for further checks with the following SetSession method.
    /// Requesting a challenge that was already requested will overwrite the previous challenge.
    #[prost(message, optional, tag="5")]
    pub challenges: ::core::option::Option<RequestChallenges>,
    /// Update the duration after which the session will be automatically invalidated.
    /// If not set, the lifetime will not be changed.
    /// Note that an expired session cannot be used for authentication anymore, but will still be listed
    /// until it is deleted.
    #[prost(message, optional, tag="6")]
    pub lifetime: ::core::option::Option<::pbjson_types::Duration>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetSessionResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    /// The current token of the session, which is required for using the session as authentication,
    /// e.g.when authenticating an OIDC auth request or SAML request.
    /// Additionally, the session token can be used as OAuth2 access token to authenticate against
    /// the Zitadel APIs.
    /// The previous token was invalidated and can no longer be used.
    #[prost(string, tag="2")]
    pub session_token: ::prost::alloc::string::String,
    /// The challenges that were requested for the session.
    /// The challenges can be used for further checks with the SetSession method.
    #[prost(message, optional, tag="3")]
    pub challenges: ::core::option::Option<Challenges>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSessionRequest {
    /// The unique identifier of the session to be terminated.
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    /// The current token of the session, previously returned on the create / update request.
    /// The token is required unless either of the following conditions is met:
    /// - the caller created the session
    /// - the authenticated user requests their own session (checked user)
    /// - the security token provided in the authorization header has the same user agent as the session
    /// - the caller is granted the permission session.delete permission on either the instance or on the checked user's organization
    #[prost(string, optional, tag="2")]
    pub session_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSessionResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Checks {
    /// Check the user by its user ID or login name.
    /// A user check can only be performed once per session and cannot be changed afterwards.
    /// On successful user check, the session's `factors` field will be updated with a `user` factor
    /// containing the checked user's ID, login name, display name, organization ID and verification time.
    /// Note that some other checks require that the user is already checked, either in the previous
    /// or the same request. For example, a password check requires that the user is already checked.
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<CheckUser>,
    /// Check the password and update the session on success.
    /// Requires that the user is already checked, either in the previous or the same request.
    /// On successful password check, the session's `factors` field will be updated with a `password` factor,
    /// containing the verification time.
    /// On failed password check id: "COMMAND-3M0fs" wll be returned.
    /// On user locked out id: "COMMAND-JLK35"/"COMMAND-SFA3t" will be returned.
    #[prost(message, optional, tag="2")]
    pub password: ::core::option::Option<CheckPassword>,
    /// Check the public key credential issued by the WebAuthN client.
    /// Requires that the user is already checked and a WebAuthN challenge to be requested,
    /// in any previous request.
    /// On successful WebAuthN check, the session's `factors` field will be updated with a `webauthn` factor,
    /// containing the verification time and if the user presence was verified.
    #[prost(message, optional, tag="3")]
    pub web_auth_n: ::core::option::Option<CheckWebAuthN>,
    /// Check the IDP intent and update the session on success.
    /// Requires that the user is already checked and an IDP intent succeeded and has not expired yet.
    /// Note that the IDP intent must be either matching the same user as checked in the session,
    /// or there must not be an external IDP linked to the intent's user.
    /// On successful IDP intent check, the session's `factors` field will be updated with an `intent` factor,
    /// containing the verification time.
    #[prost(message, optional, tag="4")]
    pub idp_intent: ::core::option::Option<CheckIdpIntent>,
    /// Check the TOTP and update the session on success.
    /// Requires that the user is already checked, either in the previous or the same request.
    /// On successful TOTP check, the session's `factors` field will be updated with a `totp` factor,
    /// containing the verification time.
    #[prost(message, optional, tag="5")]
    pub totp: ::core::option::Option<CheckTotp>,
    /// Check the OTP sent over SMS and update the session on success.
    /// Requires that the user is already checked, either in the previous or the same request.
    /// On successful OTP SMS check, the session's `factors` field will be updated with an `otp` factor,
    /// containing the verification time.
    /// Note that the OTP code is valid for a single use only and will be invalidated after a successful check.
    #[prost(message, optional, tag="6")]
    pub otp_sms: ::core::option::Option<CheckOtp>,
    /// Check the OTP sent over Email and update the session on success.
    /// Requires that the user is already checked, either in the previous or the same request.
    /// On successful OTP Email check, the session's `factors` field will be updated with an `otp` factor,
    /// containing the verification time.
    /// Note that the OTP code is valid for a single use only and will be invalidated after a successful check.
    #[prost(message, optional, tag="7")]
    pub otp_email: ::core::option::Option<CheckOtp>,
    /// Check the Recovery Code and update the session on success.
    /// Requires that the user is already checked, either in the previous or the same request.
    /// On successful Recovery Code check, the session's `factors` field will be updated with a `recovery_code` factor,
    /// containing the verification time.
    #[prost(message, optional, tag="8")]
    pub recovery_code: ::core::option::Option<CheckRecoveryCode>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckUser {
    /// Search the user either by its user ID or login name.
    #[prost(oneof="check_user::Search", tags="1, 2")]
    pub search: ::core::option::Option<check_user::Search>,
}
/// Nested message and enum types in `CheckUser`.
pub mod check_user {
    /// Search the user either by its user ID or login name.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Search {
        /// The unique identifier of the user to be checked.
        #[prost(string, tag="1")]
        UserId(::prost::alloc::string::String),
        /// The login name of the user to be checked. It will search case insensitive.
        /// Note this only checks for the computed login name and not for any organization scoped usernames.
        /// Also note that it will not check for emails or phone numbers, even if the corresponding
        /// setting is enabled. Use the user service ListUsers method to find a user by email or phone number first
        /// to obtain the user ID or login name.
        #[prost(string, tag="2")]
        LoginName(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckPassword {
    /// The password of the user to be checked.
    #[prost(string, tag="1")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckWebAuthN {
    /// The JSON representation of the public key credential issued by the WebAuthN client.
    #[prost(message, optional, tag="1")]
    pub credential_assertion_data: ::core::option::Option<::pbjson_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckIdpIntent {
    /// The ID of the idp intent, previously returned on the success response of the IDP callback.
    #[prost(string, tag="1")]
    pub idp_intent_id: ::prost::alloc::string::String,
    /// The token of the idp intent, previously returned on the success response of the IDP callback.
    #[prost(string, tag="2")]
    pub idp_intent_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckTotp {
    /// The TOTP generated by the user's TOTP authenticator app.
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckOtp {
    /// The OTP sent over SMS or Email of the user to be checked.
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckRecoveryCode {
    /// The Recovery Code of the user to be checked.
    /// The code must match the exact code previously generated for the user, including dashes if any.
    /// On successful check, the recovery code will be invalidated and cannot be used again.
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
}
include!("zitadel.session.v2.tonic.rs");
// @@protoc_insertion_point(module)