// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instance {
    /// ID is the unique identifier of the instance.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// ChangeDate is the timestamp when the instance was last changed.
    #[prost(message, optional, tag="2")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// CreationDate is the timestamp when the instance was created.
    #[prost(message, optional, tag="3")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// State is the current state of the instance.
    #[prost(enumeration="State", tag="4")]
    pub state: i32,
    /// Name is the display name of the instance.
    /// This can be changed by the instance administrator.
    #[prost(string, tag="5")]
    pub name: ::prost::alloc::string::String,
    /// Version of the system the instance is running on.
    /// This is managed by the system and cannot be changed by the instance administrator.
    #[prost(string, tag="6")]
    pub version: ::prost::alloc::string::String,
    /// CustomDomains are the domains that are assigned to the instance.
    /// The list includes auto-generated and manually added domains.
    /// They are all unique across all instances in the system.
    /// They're used to route requests to the correct instance.
    #[prost(message, repeated, tag="7")]
    pub custom_domains: ::prost::alloc::vec::Vec<CustomDomain>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomDomain {
    /// InstanceID is the unique identifier of the instance the domain belongs to.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// CreationDate is the timestamp when the domain was created.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Domain is the fully qualified domain name.
    /// It must be unique across all instances in the system.
    #[prost(string, tag="3")]
    pub domain: ::prost::alloc::string::String,
    /// Primary states whether this domain is the primary domain of the instance.
    /// Each instance must have exactly one primary domain.
    /// The primary domain is used for various purposes and acts as fallback
    /// in those cases, e.g if no explicit domain is specified.
    #[prost(bool, tag="4")]
    pub primary: bool,
    /// Generate states whether this domain was auto-generated by the system.
    /// Auto-generated domains follow a specific pattern and are created
    /// when a new instance is created.
    /// They cannot be deleted, but the primary domain can be changed
    /// to a manually added domain.
    #[prost(bool, tag="5")]
    pub generated: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Filter {
    #[prost(oneof="filter::Filter", tags="1, 2")]
    pub filter: ::core::option::Option<filter::Filter>,
}
/// Nested message and enum types in `Filter`.
pub mod filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for one or more specific instance IDs.
        #[prost(message, tag="1")]
        InIdsFilter(super::super::super::filter::v2::InIDsFilter),
        /// Filter for instances that have at least one of the specified Custom Domains.
        #[prost(message, tag="2")]
        CustomDomainsFilter(super::CustomDomainsFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomDomainsFilter {
    /// The domains to query for. All instances that have at least one of the
    /// specified domains will be returned.
    /// A maximum of 20 domains can be specified.
    #[prost(string, repeated, tag="1")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomDomainFilter {
    #[prost(oneof="custom_domain_filter::Filter", tags="1, 2, 3")]
    pub filter: ::core::option::Option<custom_domain_filter::Filter>,
}
/// Nested message and enum types in `CustomDomainFilter`.
pub mod custom_domain_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for a specific Custom Domain.
        #[prost(message, tag="1")]
        DomainFilter(super::DomainFilter),
        /// Filter whether the domain is auto-generated.
        #[prost(bool, tag="2")]
        GeneratedFilter(bool),
        /// Filter whether the domain is the primary domain of the instance.
        #[prost(bool, tag="3")]
        PrimaryFilter(bool),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainFilter {
    /// The domain to filter for.
    #[prost(string, tag="1")]
    pub domain: ::prost::alloc::string::String,
    /// The method to use for text comparison.
    /// If not specified, EQUALS is used.
    #[prost(enumeration="super::super::object::v2::TextQueryMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrustedDomain {
    /// InstanceID is the unique identifier of the instance the domain belongs to.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// The timestamp when the domain was created.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Domain is the fully qualified domain name.
    #[prost(string, tag="3")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrustedDomainFilter {
    #[prost(oneof="trusted_domain_filter::Filter", tags="1")]
    pub filter: ::core::option::Option<trusted_domain_filter::Filter>,
}
/// Nested message and enum types in `TrustedDomainFilter`.
pub mod trusted_domain_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for a specific Trusted Domain.
        #[prost(message, tag="1")]
        DomainFilter(super::DomainFilter),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum State {
    Unspecified = 0,
    Creating = 1,
    Running = 2,
    Stopping = 3,
    Stopped = 4,
}
impl State {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STATE_UNSPECIFIED",
            Self::Creating => "STATE_CREATING",
            Self::Running => "STATE_RUNNING",
            Self::Stopping => "STATE_STOPPING",
            Self::Stopped => "STATE_STOPPED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "STATE_CREATING" => Some(Self::Creating),
            "STATE_RUNNING" => Some(Self::Running),
            "STATE_STOPPING" => Some(Self::Stopping),
            "STATE_STOPPED" => Some(Self::Stopped),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FieldName {
    Unspecified = 0,
    Id = 1,
    Name = 2,
    CreationDate = 3,
}
impl FieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FIELD_NAME_UNSPECIFIED",
            Self::Id => "FIELD_NAME_ID",
            Self::Name => "FIELD_NAME_NAME",
            Self::CreationDate => "FIELD_NAME_CREATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "FIELD_NAME_ID" => Some(Self::Id),
            "FIELD_NAME_NAME" => Some(Self::Name),
            "FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DomainFieldName {
    Unspecified = 0,
    Domain = 1,
    Primary = 2,
    Generated = 3,
    CreationDate = 4,
}
impl DomainFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOMAIN_FIELD_NAME_UNSPECIFIED",
            Self::Domain => "DOMAIN_FIELD_NAME_DOMAIN",
            Self::Primary => "DOMAIN_FIELD_NAME_PRIMARY",
            Self::Generated => "DOMAIN_FIELD_NAME_GENERATED",
            Self::CreationDate => "DOMAIN_FIELD_NAME_CREATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOMAIN_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "DOMAIN_FIELD_NAME_DOMAIN" => Some(Self::Domain),
            "DOMAIN_FIELD_NAME_PRIMARY" => Some(Self::Primary),
            "DOMAIN_FIELD_NAME_GENERATED" => Some(Self::Generated),
            "DOMAIN_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrustedDomainFieldName {
    Unspecified = 0,
    Domain = 1,
    CreationDate = 2,
}
impl TrustedDomainFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRUSTED_DOMAIN_FIELD_NAME_UNSPECIFIED",
            Self::Domain => "TRUSTED_DOMAIN_FIELD_NAME_DOMAIN",
            Self::CreationDate => "TRUSTED_DOMAIN_FIELD_NAME_CREATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRUSTED_DOMAIN_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "TRUSTED_DOMAIN_FIELD_NAME_DOMAIN" => Some(Self::Domain),
            "TRUSTED_DOMAIN_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteInstanceRequest {
    /// InstanceID is the unique ID of the instance to be deleted.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteInstanceResponse {
    /// DeletionDate is the timestamp when the instance was deleted.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInstanceRequest {
    /// InstanceID is the unique ID of the instance to be retrieved.
    /// If not set, the instance in the current context (e.g. identified by the host header) will be returned.
    /// If an ID is set, the caller must have additional permissions.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInstanceResponse {
    /// The instance matching the instance ID
    #[prost(message, optional, tag="1")]
    pub instance: ::core::option::Option<Instance>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateInstanceRequest {
    /// InstanceID is the unique ID of the instance to be updated.
    /// If not set, the instance in the current context (e.g. identified by the host header) will be changed.
    /// If an ID is set, the caller must have additional permissions.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// InstanceName is the new name of the instance to be set.
    #[prost(string, tag="2")]
    pub instance_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateInstanceResponse {
    /// ChangeDate is the timestamp when the instance was last changed.
    /// In case the instance was not changed during the call, the previous change date is returned.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInstancesRequest {
    /// Paginate through the results using a limit, offset and sorting.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// The field the result is sorted by.
    #[prost(enumeration="FieldName", tag="2")]
    pub sorting_column: i32,
    /// Filter the instances to be returned.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInstancesResponse {
    /// The instances matching the query.
    #[prost(message, repeated, tag="1")]
    pub instances: ::prost::alloc::vec::Vec<Instance>,
    /// Contains the total number of instances matching the query and the applied limit.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddCustomDomainRequest {
    /// InstanceID is the unique ID of the instance to which the domain will be added.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// Custom Domain to add to the instance.
    /// Must be a valid domain name.
    /// Once the domain is added, it will be used to route requests to this instance.
    #[prost(string, tag="2")]
    pub custom_domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddCustomDomainResponse {
    /// CreationDate is the timestamp when the domain was added.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveCustomDomainRequest {
    /// InstanceID is the unique ID of the instance from which the domain will be removed.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// CustomDomain is the the domain to remove from the instance.
    #[prost(string, tag="2")]
    pub custom_domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveCustomDomainResponse {
    /// DeletionDate is the timestamp when the domain was removed.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCustomDomainsRequest {
    /// InstanceID is the unique ID of the instance  whose domains will be listed.
    /// If not set, the instance in the current context (e.g. identified by the host header) will be used.
    /// If an ID is set, the caller must have additional permissions.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// Paginate and sort the results using a limit, offset and sorting.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// The field the result is sorted by.
    #[prost(enumeration="DomainFieldName", tag="3")]
    pub sorting_column: i32,
    /// Filter the domains to be returned.
    #[prost(message, repeated, tag="4")]
    pub filters: ::prost::alloc::vec::Vec<CustomDomainFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCustomDomainsResponse {
    /// The list of Custom Domains matching the query.
    #[prost(message, repeated, tag="1")]
    pub domains: ::prost::alloc::vec::Vec<CustomDomain>,
    /// Contains the total number of domains matching the query and the applied limit.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddTrustedDomainRequest {
    /// InstanceID is the unique ID of the instance to which the Trusted Domain will be added.
    /// If not set, the instance in the current context (e.g. identified by the host header) will be used.
    /// If an ID is set, the caller must have additional permissions.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// Trusted Domain to be added to the instance.
    /// Must be a valid domain name.
    /// Once the domain is added, it can be used in API responses like OIDC discovery,
    /// email templates, and more.
    /// This can be used in cases where the API is accessed through a different domain
    /// than the Custom Domain, e.g. proxy setups and custom login UIs.
    /// Unlike Custom Domains, Trusted Domains are not used to route requests to this instance
    /// and therefore do not need to be uniquely assigned to an instance.
    #[prost(string, tag="2")]
    pub trusted_domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddTrustedDomainResponse {
    /// CreationDate is the timestamp when the Trusted Domain was added.
    #[prost(message, optional, tag="1")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveTrustedDomainRequest {
    /// InstanceID is the unique ID of the instance from which the Trusted Domain will be removed.
    /// If not set, the instance in the current context (e.g. identified by the host header) will be used.
    /// If an ID is set, the caller must have additional permissions.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// The Trusted Domain to remove from the instance.
    #[prost(string, tag="2")]
    pub trusted_domain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveTrustedDomainResponse {
    /// DeletionDate is the timestamp when the Trusted Domain was removed.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTrustedDomainsRequest {
    /// InstanceID is the unique ID of the instance whose Trusted Domains will be listed.
    /// If not set, the instance in the current context (e.g. identified by the host header) will be used.
    /// If an ID is set, the caller must have additional permissions.
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    /// Paginate and sort the results using a limit, offset and sorting.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// The field the result is sorted by.
    #[prost(enumeration="TrustedDomainFieldName", tag="3")]
    pub sorting_column: i32,
    /// Filter the domains to be returned.
    #[prost(message, repeated, tag="4")]
    pub filters: ::prost::alloc::vec::Vec<TrustedDomainFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTrustedDomainsResponse {
    /// The list of Trusted Domains matching the query.
    #[prost(message, repeated, tag="1")]
    pub trusted_domain: ::prost::alloc::vec::Vec<TrustedDomain>,
    /// Contains the total number of domains matching the query and the applied limit.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
}
include!("zitadel.instance.v2.tonic.rs");
// @@protoc_insertion_point(module)