// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Target {
    /// The unique identifier of the target.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// The timestamp of the target creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The timestamp of the last change to the target.
    #[prost(message, optional, tag="3")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Display name of the target.
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    /// Timeout defines the duration until Zitadel cancels the execution.
    /// If the target doesn't respond before this timeout expires, the the connection is closed and the action fails. Depending on the target type and possible setting on `interrupt_on_error` following targets will not be called. In case of a `rest_async` target only this specific target will fail, without any influence on other targets of the same execution.
    #[prost(message, optional, tag="8")]
    pub timeout: ::core::option::Option<::pbjson_types::Duration>,
    /// The URL that will be called in case of an execution.
    #[prost(string, tag="9")]
    pub endpoint: ::prost::alloc::string::String,
    /// The current signing key used to sign the request sent to the target.
    /// The key can be used to verify the integrity and authenticity of the request
    /// on the receiver side. The key should be treated as a secret and only known to Zitadel and the receiver.
    /// The signature is included in the request header `X-ZITADEL-Signature`
    /// and calculated over the raw body of the request using HMAC with SHA256.
    #[prost(string, tag="10")]
    pub signing_key: ::prost::alloc::string::String,
    /// Payload type defines how the payload is formatted and secured.
    /// The default is `PAYLOAD_TYPE_JSON`, which sends the payload as JSON in the body of the request.
    /// For integrity and authenticity a signature is included in the header `X-ZITADEL-Signature`.
    /// You can also choose to send the payload as a JWT (`PAYLOAD_TYPE_JWT`), which sends
    /// the payload as a signed JWT in the body of the request. This allows the receiver to verify
    /// the authenticity and integrity of the payload using the signing key (published on the JWKS URL).
    /// If you need encryption as well, you can choose `PAYLOAD_TYPE_JWE`, which sends the payload
    /// as an encrypted JWT in the body of the request. You can provide your own public key for encryption.
    #[prost(enumeration="PayloadType", tag="11")]
    pub payload_type: i32,
    /// Defines the target type and how the response of the target is treated.
    #[prost(oneof="target::TargetType", tags="5, 6, 7")]
    pub target_type: ::core::option::Option<target::TargetType>,
}
/// Nested message and enum types in `Target`.
pub mod target {
    /// Defines the target type and how the response of the target is treated.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum TargetType {
        #[prost(message, tag="5")]
        RestWebhook(super::RestWebhook),
        #[prost(message, tag="6")]
        RestCall(super::RestCall),
        #[prost(message, tag="7")]
        RestAsync(super::RestAsync),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestWebhook {
    /// Define if any error stops the whole execution. By default the process continues as normal.
    #[prost(bool, tag="1")]
    pub interrupt_on_error: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestCall {
    /// Define if any error stops the whole execution. By default the process continues as normal.
    #[prost(bool, tag="1")]
    pub interrupt_on_error: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestAsync {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicKey {
    /// KeyID is the unique identifier of the public key.
    /// It's also used as the `kid` field in the JWE header when the payload type is set to `PAYLOAD_TYPE_JWE`.
    #[prost(string, tag="1")]
    pub key_id: ::prost::alloc::string::String,
    /// Active indicates whether the public key is active and used for payload encryption.
    /// Only one public key can be active at a time.
    #[prost(bool, tag="2")]
    pub active: bool,
    /// The public key in PEM format.
    #[prost(bytes="vec", tag="3")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// Fingerprint is the fingerprint of the public key. It's prefixed with the hashing algorithm used
    /// and base64 encoded without padding, e.g. `SHA256:STqK+Sd4qgdu+UjiwI8NBjOD6P7UqQ42EZYIdySEyTw`.
    /// The fingerprint can be used to easily compare the public key with other sources.
    #[prost(string, tag="4")]
    pub fingerprint: ::prost::alloc::string::String,
    /// ExpirationDate is the timestamp when the public key automatically expires and
    /// no longer will be used for payload encryption, even when active.
    /// Be sure to upload and activate a new public key before the expiration date
    /// to avoid failed executions.
    #[prost(message, optional, tag="5")]
    pub expiration_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// CreationDate is the timestamp when the the public key was uploaded.
    #[prost(message, optional, tag="6")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// ChangeDate is the timestamp when the public key was last changed, e.g. activated or deactivated.
    #[prost(message, optional, tag="7")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PayloadType {
    Unspecified = 0,
    /// PAYLOAD_TYPE_JSON will send the payload as JSON in the body of the request.
    /// For integrity and authenticity a signature is included in the header `X-ZITADEL-Signature`.
    /// This is the current default, for backwards compatibility reasons.
    Json = 1,
    /// PAYLOAD_TYPE_JWT will send the payload as JSON Web Token (JWT) in the body of the request.
    /// This allows the receiver to verify the authenticity and integrity of the payload
    /// using the signing key (published on the JWKS URL).
    Jwt = 2,
    /// PAYLOAD_TYPE_JWE will send the payload as Encrypted JWT (JWE) in the body of the request.
    /// This allows additional security, e.g when passing sensitive information.
    /// You can provide your own public key for encryption.
    Jwe = 3,
}
impl PayloadType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PAYLOAD_TYPE_UNSPECIFIED",
            Self::Json => "PAYLOAD_TYPE_JSON",
            Self::Jwt => "PAYLOAD_TYPE_JWT",
            Self::Jwe => "PAYLOAD_TYPE_JWE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PAYLOAD_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "PAYLOAD_TYPE_JSON" => Some(Self::Json),
            "PAYLOAD_TYPE_JWT" => Some(Self::Jwt),
            "PAYLOAD_TYPE_JWE" => Some(Self::Jwe),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Execution {
    /// The condition under which the execution is triggered.
    #[prost(message, optional, tag="1")]
    pub condition: ::core::option::Option<Condition>,
    /// The timestamp of the execution creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// The timestamp of the last change to the execution.
    #[prost(message, optional, tag="3")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Ordered list of targets called during the execution.
    /// The order of the targets in this list defines the order of execution.
    /// If one of the targets fails, depending on the target's type and settings,
    /// the execution might be interrupted and the following targets will not be called.
    #[prost(string, repeated, tag="4")]
    pub targets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Condition {
    /// Condition-types under which conditions the execution should happen, only one possible.
    #[prost(oneof="condition::ConditionType", tags="1, 2, 3, 4")]
    pub condition_type: ::core::option::Option<condition::ConditionType>,
}
/// Nested message and enum types in `Condition`.
pub mod condition {
    /// Condition-types under which conditions the execution should happen, only one possible.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ConditionType {
        /// Condition-type to execute if a request on the defined API point happens.
        #[prost(message, tag="1")]
        Request(super::RequestExecution),
        /// Condition-type to execute on response if a request on the defined API point happens.
        #[prost(message, tag="2")]
        Response(super::ResponseExecution),
        /// Condition-type to execute if function is used, replaces actions v1.
        #[prost(message, tag="3")]
        Function(super::FunctionExecution),
        /// Condition-type to execute if an event is created in the system.
        #[prost(message, tag="4")]
        Event(super::EventExecution),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestExecution {
    /// Condition for the request execution. Only one is possible.
    #[prost(oneof="request_execution::Condition", tags="1, 2, 3")]
    pub condition: ::core::option::Option<request_execution::Condition>,
}
/// Nested message and enum types in `RequestExecution`.
pub mod request_execution {
    /// Condition for the request execution. Only one is possible.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Condition {
        /// Define a GRPC-method as condition.
        /// When a request to this method happens, the execution is triggered.
        #[prost(string, tag="1")]
        Method(::prost::alloc::string::String),
        /// Define a GRPC-service as condition.
        /// When a request to any method of this service happens, the execution is triggered.
        #[prost(string, tag="2")]
        Service(::prost::alloc::string::String),
        /// Define all calls as condition.
        /// When a call to any available service happens, the execution is triggered.
        #[prost(bool, tag="3")]
        All(bool),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResponseExecution {
    /// Condition for the response execution. Only one is possible.
    #[prost(oneof="response_execution::Condition", tags="1, 2, 3")]
    pub condition: ::core::option::Option<response_execution::Condition>,
}
/// Nested message and enum types in `ResponseExecution`.
pub mod response_execution {
    /// Condition for the response execution. Only one is possible.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Condition {
        /// Define a GRPC-method as condition.
        /// Before a response is returned to the client from this method, the execution is triggered.
        #[prost(string, tag="1")]
        Method(::prost::alloc::string::String),
        /// Define a GRPC-service as condition.
        /// Before a response is returned to the client from any method of this service, the execution is triggered.
        #[prost(string, tag="2")]
        Service(::prost::alloc::string::String),
        /// Define all calls as condition.
        /// Before a response is returned to the client from any available service,
        /// the execution is triggered.
        #[prost(bool, tag="3")]
        All(bool),
    }
}
/// Executed on the specified function
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FunctionExecution {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventExecution {
    /// Condition for the event execution. Only one is possible.
    #[prost(oneof="event_execution::Condition", tags="1, 2, 3")]
    pub condition: ::core::option::Option<event_execution::Condition>,
}
/// Nested message and enum types in `EventExecution`.
pub mod event_execution {
    /// Condition for the event execution. Only one is possible.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Condition {
        /// Define a specific event as condition.
        /// After this event is created, the execution is triggered.
        #[prost(string, tag="1")]
        Event(::prost::alloc::string::String),
        /// Define an event group as condition.
        /// After any event under this group is created, the execution is triggered.
        #[prost(string, tag="2")]
        Group(::prost::alloc::string::String),
        /// Define all events as condition.
        /// After any event is created, the execution is triggered.
        #[prost(bool, tag="3")]
        All(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionSearchFilter {
    #[prost(oneof="execution_search_filter::Filter", tags="1, 2, 3")]
    pub filter: ::core::option::Option<execution_search_filter::Filter>,
}
/// Nested message and enum types in `ExecutionSearchFilter`.
pub mod execution_search_filter {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for executions that are executed when certain conditions are met.
        #[prost(message, tag="1")]
        InConditionsFilter(super::InConditionsFilter),
        /// Filter for executions of a certain type.
        #[prost(message, tag="2")]
        ExecutionTypeFilter(super::ExecutionTypeFilter),
        /// Filter for executions that include a specific target.
        #[prost(message, tag="3")]
        TargetFilter(super::TargetFilter),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InConditionsFilter {
    /// Defines the conditions to query for.
    #[prost(message, repeated, tag="1")]
    pub conditions: ::prost::alloc::vec::Vec<Condition>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecutionTypeFilter {
    /// Defines the type to query for.
    #[prost(enumeration="ExecutionType", tag="1")]
    pub execution_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TargetFilter {
    /// Defines the id of the target that needs to be part of the execution.
    #[prost(string, tag="1")]
    pub target_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TargetSearchFilter {
    #[prost(oneof="target_search_filter::Filter", tags="1, 2")]
    pub filter: ::core::option::Option<target_search_filter::Filter>,
}
/// Nested message and enum types in `TargetSearchFilter`.
pub mod target_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter for targets with a specific name.
        #[prost(message, tag="1")]
        TargetNameFilter(super::TargetNameFilter),
        /// Filter for targets with specific ids.
        #[prost(message, tag="2")]
        InTargetIdsFilter(super::InTargetIDsFilter),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TargetNameFilter {
    /// Defines the name of the target to query for.
    #[prost(string, tag="1")]
    pub target_name: ::prost::alloc::string::String,
    /// Defines which text comparison method used for the name query.
    #[prost(enumeration="super::super::filter::v2::TextFilterMethod", tag="2")]
    pub method: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InTargetIDsFilter {
    /// Defines the ids to query for.
    #[prost(string, repeated, tag="1")]
    pub target_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicKeySearchFilter {
    #[prost(oneof="public_key_search_filter::Filter", tags="1, 2, 3")]
    pub filter: ::core::option::Option<public_key_search_filter::Filter>,
}
/// Nested message and enum types in `PublicKeySearchFilter`.
pub mod public_key_search_filter {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Filter {
        /// Filter the keys by one or multiple ids.
        #[prost(message, tag="1")]
        KeyIdsFilter(super::super::super::filter::v2::InIDsFilter),
        /// Filter the keys by their active status.
        #[prost(bool, tag="2")]
        ActiveFilter(bool),
        /// Filter the keys by their expiration status.
        #[prost(message, tag="3")]
        ExpirationDateFilter(super::super::super::filter::v2::TimestampFilter),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TargetFieldName {
    Unspecified = 0,
    Id = 1,
    CreatedDate = 2,
    ChangedDate = 3,
    Name = 4,
    TargetType = 5,
    Url = 6,
    Timeout = 7,
    InterruptOnError = 8,
}
impl TargetFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TARGET_FIELD_NAME_UNSPECIFIED",
            Self::Id => "TARGET_FIELD_NAME_ID",
            Self::CreatedDate => "TARGET_FIELD_NAME_CREATED_DATE",
            Self::ChangedDate => "TARGET_FIELD_NAME_CHANGED_DATE",
            Self::Name => "TARGET_FIELD_NAME_NAME",
            Self::TargetType => "TARGET_FIELD_NAME_TARGET_TYPE",
            Self::Url => "TARGET_FIELD_NAME_URL",
            Self::Timeout => "TARGET_FIELD_NAME_TIMEOUT",
            Self::InterruptOnError => "TARGET_FIELD_NAME_INTERRUPT_ON_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TARGET_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "TARGET_FIELD_NAME_ID" => Some(Self::Id),
            "TARGET_FIELD_NAME_CREATED_DATE" => Some(Self::CreatedDate),
            "TARGET_FIELD_NAME_CHANGED_DATE" => Some(Self::ChangedDate),
            "TARGET_FIELD_NAME_NAME" => Some(Self::Name),
            "TARGET_FIELD_NAME_TARGET_TYPE" => Some(Self::TargetType),
            "TARGET_FIELD_NAME_URL" => Some(Self::Url),
            "TARGET_FIELD_NAME_TIMEOUT" => Some(Self::Timeout),
            "TARGET_FIELD_NAME_INTERRUPT_ON_ERROR" => Some(Self::InterruptOnError),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionType {
    Unspecified = 0,
    Request = 1,
    Response = 2,
    Event = 3,
    Function = 4,
}
impl ExecutionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXECUTION_TYPE_UNSPECIFIED",
            Self::Request => "EXECUTION_TYPE_REQUEST",
            Self::Response => "EXECUTION_TYPE_RESPONSE",
            Self::Event => "EXECUTION_TYPE_EVENT",
            Self::Function => "EXECUTION_TYPE_FUNCTION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_TYPE_REQUEST" => Some(Self::Request),
            "EXECUTION_TYPE_RESPONSE" => Some(Self::Response),
            "EXECUTION_TYPE_EVENT" => Some(Self::Event),
            "EXECUTION_TYPE_FUNCTION" => Some(Self::Function),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionFieldName {
    Unspecified = 0,
    Id = 1,
    CreatedDate = 2,
    ChangedDate = 3,
}
impl ExecutionFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXECUTION_FIELD_NAME_UNSPECIFIED",
            Self::Id => "EXECUTION_FIELD_NAME_ID",
            Self::CreatedDate => "EXECUTION_FIELD_NAME_CREATED_DATE",
            Self::ChangedDate => "EXECUTION_FIELD_NAME_CHANGED_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_FIELD_NAME_ID" => Some(Self::Id),
            "EXECUTION_FIELD_NAME_CREATED_DATE" => Some(Self::CreatedDate),
            "EXECUTION_FIELD_NAME_CHANGED_DATE" => Some(Self::ChangedDate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PublicKeyFieldName {
    /// Unspecified field name.
    Unspecified = 0,
    /// Sort by creation date.
    CreationDate = 1,
    /// Sort by change date.
    ChangeDate = 2,
    /// Sort by expiration date.
    ExpirationDate = 3,
}
impl PublicKeyFieldName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PUBLIC_KEY_FIELD_NAME_UNSPECIFIED",
            Self::CreationDate => "PUBLIC_KEY_FIELD_NAME_CREATION_DATE",
            Self::ChangeDate => "PUBLIC_KEY_FIELD_NAME_CHANGE_DATE",
            Self::ExpirationDate => "PUBLIC_KEY_FIELD_NAME_EXPIRATION_DATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PUBLIC_KEY_FIELD_NAME_UNSPECIFIED" => Some(Self::Unspecified),
            "PUBLIC_KEY_FIELD_NAME_CREATION_DATE" => Some(Self::CreationDate),
            "PUBLIC_KEY_FIELD_NAME_CHANGE_DATE" => Some(Self::ChangeDate),
            "PUBLIC_KEY_FIELD_NAME_EXPIRATION_DATE" => Some(Self::ExpirationDate),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTargetRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Timeout defines the duration until Zitadel cancels the execution.
    /// If the target doesn't respond before this timeout expires, then the connection is closed and the action fails.
    /// Depending on the target type and possible setting on `interrupt_on_error` following targets will not be called.
    /// In case of a `rest_async` target only this specific target will fail, without any influence on other targets of the same execution.
    /// The maximum timeout is 270 seconds or 4.5 minutes.
    #[prost(message, optional, tag="5")]
    pub timeout: ::core::option::Option<::pbjson_types::Duration>,
    /// The URL of the endpoint to call.
    #[prost(string, tag="6")]
    pub endpoint: ::prost::alloc::string::String,
    /// Payload type defines how the payload is formatted and secured.
    /// The default is `PAYLOAD_TYPE_JSON`, which sends the payload as JSON in the body of the request.
    /// For integrity and authenticity a signature is included in the header `X-ZITADEL-Signature`.
    /// You can also choose to send the payload as a JWT (`PAYLOAD_TYPE_JWT`), which sends
    /// the payload as a signed JWT in the body of the request. This allows the receiver to verify
    /// the authenticity and integrity of the payload using the signing key.
    /// If you need encryption as well, you can choose `PAYLOAD_TYPE_JWE`, which sends the payload
    /// as an encrypted JWT in the body of the request. You can provide your own public key for encryption.
    #[prost(enumeration="PayloadType", tag="7")]
    pub payload_type: i32,
    /// Defines the target type and how the response of the target is treated.
    #[prost(oneof="create_target_request::TargetType", tags="2, 3, 4")]
    pub target_type: ::core::option::Option<create_target_request::TargetType>,
}
/// Nested message and enum types in `CreateTargetRequest`.
pub mod create_target_request {
    /// Defines the target type and how the response of the target is treated.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum TargetType {
        /// The HTTP call to this target will be a POST request.
        /// The response of the target will only be checked for the status code.
        /// The returned body will be ignored.
        /// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
        /// the execution will be aborted and no further targets will be called.
        #[prost(message, tag="2")]
        RestWebhook(super::RestWebhook),
        /// The HTTP call to this target will be a POST request.
        /// The response of the target will be checked for the status code and the body.
        /// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
        /// the execution will be aborted and no further targets will be called.
        /// In case of a successful status code (2xx) the body will be parsed and mapped.
        /// This allows to modify the payload of request and response executions.
        #[prost(message, tag="3")]
        RestCall(super::RestCall),
        /// The HTTP call to this target will be a POST request.
        /// The call is sent asynchronously and Zitadel does not wait for the response.
        /// The response of the target is ignored, no status or body is checked.
        /// This is typically used for executions of type "events".
        #[prost(message, tag="4")]
        RestAsync(super::RestAsync),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTargetResponse {
    /// The unique identifier of the newly created target.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// The timestamp of the target creation.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Key used to sign and check payload sent to the target.
    /// The key can be used to verify the integrity and authenticity of the request
    /// on the receiver side. The key should be treated as a secret and only known to Zitadel and the receiver.
    /// The signature is included in the request header `X-ZITADEL-Signature`
    /// and calculated over the raw body of the request using HMAC with SHA256.
    #[prost(string, tag="3")]
    pub signing_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTargetRequest {
    /// The unique identifier of the target to update.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Optionally, update the name of the target.
    /// If not set, the name will not be changed.
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// Timeout defines the duration until Zitadel cancels the execution.
    /// If the target doesn't respond before this timeout expires, then the connection is closed and the action fails.
    /// Depending on the target type and possible setting on `interrupt_on_error` following targets will not be called.
    /// In case of a `rest_async` target only this specific target will fail, without any influence on other targets of the same execution.
    /// The maximum timeout is 270 seconds or 4.5 minutes.
    /// If not set, the timeout will not be changed.
    #[prost(message, optional, tag="6")]
    pub timeout: ::core::option::Option<::pbjson_types::Duration>,
    /// The new URL of the endpoint to call.
    /// If not set, the endpoint will not be changed.
    #[prost(string, optional, tag="7")]
    pub endpoint: ::core::option::Option<::prost::alloc::string::String>,
    /// Regenerate the key used for signing and checking the payload sent to the target.
    /// Set the graceful period for the existing key. During that time, the previous
    /// signing key and the new one will be used to sign the request to allow you a smooth
    /// transition onf your API.
    ///
    /// Note that we currently only allow an immediate rotation ("0s") and will support
    /// longer expirations in the future.
    #[prost(message, optional, tag="8")]
    pub expiration_signing_key: ::core::option::Option<::pbjson_types::Duration>,
    /// Payload type defines how the payload is formatted and secured.
    /// The default is `PAYLOAD_TYPE_JSON`, which sends the payload as JSON in the body of the request.
    /// For integrity and authenticity a signature is included in the header `X-ZITADEL-Signature`.
    /// You can also choose to send the payload as a JWT (`PAYLOAD_TYPE_JWT`), which sends
    /// the payload as a signed JWT in the body of the request. This allows the receiver to verify
    /// the authenticity and integrity of the payload using the signing key.
    /// If you need encryption as well, you can choose `PAYLOAD_TYPE_JWE`, which sends the payload
    /// as an encrypted JWT in the body of the request. You can provide your own public key for encryption.
    /// If unspecified, the payload type will not be changed.
    #[prost(enumeration="PayloadType", tag="9")]
    pub payload_type: i32,
    /// Defines the target type and how the response of the target is treated.
    #[prost(oneof="update_target_request::TargetType", tags="3, 4, 5")]
    pub target_type: ::core::option::Option<update_target_request::TargetType>,
}
/// Nested message and enum types in `UpdateTargetRequest`.
pub mod update_target_request {
    /// Defines the target type and how the response of the target is treated.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum TargetType {
        /// The HTTP call to this target will be a POST request.
        /// The response of the target will only be checked for the status code.
        /// The returned body will be ignored.
        /// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
        /// the execution will be aborted and no further targets will be called.
        #[prost(message, tag="3")]
        RestWebhook(super::RestWebhook),
        /// The HTTP call to this target will be a POST request.
        /// The response of the target will be checked for the status code and the body.
        /// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
        /// the execution will be aborted and no further targets will be called.
        /// In case of a successful status code (2xx) the body will be parsed and mapped.
        /// This allows to modify the payload of request and response executions.
        #[prost(message, tag="4")]
        RestCall(super::RestCall),
        /// The HTTP call to this target will be a POST request.
        /// The call is sent asynchronously and Zitadel does not wait for the response.
        /// The response of the target is ignored, no status or body is checked.
        /// This is typically used for executions of type "events".
        #[prost(message, tag="5")]
        RestAsync(super::RestAsync),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTargetResponse {
    /// The timestamp of the change of the target.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Key used to sign and check payload sent to the target.
    /// The key can be used to verify the integrity and authenticity of the request
    /// on the receiver side. The key should be treated as a secret and only known to Zitadel and the receiver.
    /// The signature is included in the request header `X-ZITADEL-Signature`
    /// and calculated over the raw body of the request using HMAC with SHA256.
    /// The key is only returned if expirationSigningKey was set in the request.
    #[prost(string, optional, tag="2")]
    pub signing_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTargetRequest {
    /// The unique identifier of the target to delete.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTargetResponse {
    /// The timestamp of the deletion of the target.
    /// Note that the deletion date is only guaranteed to be set if the deletion was successful during the request.
    /// In case the deletion occurred in a previous request, the deletion date might be empty.
    #[prost(message, optional, tag="3")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTargetRequest {
    /// The unique identifier of the target to retrieve.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTargetResponse {
    #[prost(message, optional, tag="1")]
    pub target: ::core::option::Option<Target>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTargetsRequest {
    /// List limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// The field the result is sorted by. The default is the creation date. Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="TargetFieldName", optional, tag="2")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<TargetSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTargetsResponse {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// List of all targets matching the query.
    #[prost(message, repeated, tag="2")]
    pub targets: ::prost::alloc::vec::Vec<Target>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddPublicKeyRequest {
    /// The unique identifier of the target to add the public key to.
    #[prost(string, tag="1")]
    pub target_id: ::prost::alloc::string::String,
    /// The public key in PEM format. It must be either an RSA or an EC public key.
    #[prost(bytes="vec", tag="2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// Optional expiration date of the public key.
    /// After the expiration date, the key will be automatically deactivated and no longer used for payload encryption.
    /// Be sure to activate a new key before the current active key expires to avoid interruptions.
    /// If not set, the key will not expire.
    #[prost(message, optional, tag="3")]
    pub expiration_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddPublicKeyResponse {
    /// The KeyID is the unique identifier of the newly added public key.
    /// The ID is also used a `kid` in the JWT header for payload encryption.
    /// This allows the target to identify the correct key to use for decryption.
    #[prost(string, tag="1")]
    pub key_id: ::prost::alloc::string::String,
    /// CreationDate represents the timestamp of the public key addition.
    #[prost(message, optional, tag="2")]
    pub creation_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivatePublicKeyRequest {
    /// TargetID is the unique identifier of the target to activate the public key for.
    #[prost(string, tag="1")]
    pub target_id: ::prost::alloc::string::String,
    /// KeyID is the unique identifier of the public key to activate.
    #[prost(string, tag="2")]
    pub key_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivatePublicKeyResponse {
    /// ChangeDate is the timestamp of the public key's activation.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivatePublicKeyRequest {
    /// TargetID is the unique identifier of the target to deactivate the public key for.
    #[prost(string, tag="1")]
    pub target_id: ::prost::alloc::string::String,
    /// KeyID is the unique identifier of the public key to deactivate.
    #[prost(string, tag="2")]
    pub key_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeactivatePublicKeyResponse {
    /// ChangeDate is the timestamp of the public key's deactivation.
    #[prost(message, optional, tag="1")]
    pub change_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemovePublicKeyRequest {
    /// TargetID is the unique identifier of the target to remove the public key from.
    #[prost(string, tag="1")]
    pub target_id: ::prost::alloc::string::String,
    /// KeyID is the unique identifier of the public key to remove.
    #[prost(string, tag="2")]
    pub key_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemovePublicKeyResponse {
    /// DeletionDate is the timestamp of the public key removal.
    #[prost(message, optional, tag="1")]
    pub deletion_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPublicKeysRequest {
    /// TargetID is the unique identifier of the target to list the public keys for.
    #[prost(string, tag="1")]
    pub target_id: ::prost::alloc::string::String,
    /// List limitations and ordering.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// The field the result is sorted by. The default is the creation date.
    /// Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="PublicKeyFieldName", tag="3")]
    pub sorting_column: i32,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="4")]
    pub filters: ::prost::alloc::vec::Vec<PublicKeySearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPublicKeysResponse {
    /// List limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// List of all public keys for the target.
    #[prost(message, repeated, tag="2")]
    pub public_keys: ::prost::alloc::vec::Vec<PublicKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetExecutionRequest {
    /// Condition defining when the execution should be used.
    #[prost(message, optional, tag="1")]
    pub condition: ::core::option::Option<Condition>,
    /// Ordered list of targets called during the execution.
    #[prost(string, repeated, tag="2")]
    pub targets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetExecutionResponse {
    /// The timestamp of the execution set.
    #[prost(message, optional, tag="1")]
    pub set_date: ::core::option::Option<::pbjson_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListExecutionsRequest {
    /// List limitations and ordering.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationRequest>,
    /// The field the result is sorted by. The default is the creation date.
    /// Beware that if you change this, your result pagination might be inconsistent.
    #[prost(enumeration="ExecutionFieldName", optional, tag="2")]
    pub sorting_column: ::core::option::Option<i32>,
    /// Define the criteria to query for.
    #[prost(message, repeated, tag="3")]
    pub filters: ::prost::alloc::vec::Vec<ExecutionSearchFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListExecutionsResponse {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::filter::v2::PaginationResponse>,
    /// List of all executions matching the query.
    #[prost(message, repeated, tag="2")]
    pub executions: ::prost::alloc::vec::Vec<Execution>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListExecutionFunctionsRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListExecutionFunctionsResponse {
    /// All available functions to use in conditions.
    #[prost(string, repeated, tag="1")]
    pub functions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListExecutionMethodsRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListExecutionMethodsResponse {
    /// All available methods to use in conditions.
    #[prost(string, repeated, tag="1")]
    pub methods: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListExecutionServicesRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListExecutionServicesResponse {
    /// All available services to use in conditions.
    #[prost(string, repeated, tag="1")]
    pub services: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
include!("zitadel.action.v2.tonic.rs");
// @@protoc_insertion_point(module)