// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResourceOwnerType {
    Unspecified = 0,
    Instance = 1,
    Org = 2,
}
impl ResourceOwnerType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RESOURCE_OWNER_TYPE_UNSPECIFIED",
            Self::Instance => "RESOURCE_OWNER_TYPE_INSTANCE",
            Self::Org => "RESOURCE_OWNER_TYPE_ORG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RESOURCE_OWNER_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "RESOURCE_OWNER_TYPE_INSTANCE" => Some(Self::Instance),
            "RESOURCE_OWNER_TYPE_ORG" => Some(Self::Org),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BrandingSettings {
    /// Theme used for light mode.
    #[prost(message, optional, tag="1")]
    pub light_theme: ::core::option::Option<Theme>,
    /// Theme used for dark mode.
    #[prost(message, optional, tag="2")]
    pub dark_theme: ::core::option::Option<Theme>,
    /// The url where the font is served.
    #[prost(string, tag="3")]
    pub font_url: ::prost::alloc::string::String,
    /// If enabled, the organization suffix will be hidden on the login form if the scope \"urn:zitadel:iam:org:domain:primary:{domainname}\" is used.
    #[prost(bool, tag="4")]
    pub hide_login_name_suffix: bool,
    /// If enabled, the Zitadel logo will not be displayed on the login screen.
    #[prost(bool, tag="5")]
    pub disable_watermark: bool,
    /// ResourceOwnerType returns if the setting is managed on the organization explicitly or
    /// fell back on the instance settings.
    #[prost(enumeration="ResourceOwnerType", tag="6")]
    pub resource_owner_type: i32,
    /// States which themes will be used. If auto is selected, the theme will be changed based on the users system preferences.
    /// You can also choose to only allow dark or light theme.
    #[prost(enumeration="ThemeMode", tag="7")]
    pub theme_mode: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Theme {
    /// The hex value for primary color.
    #[prost(string, tag="1")]
    pub primary_color: ::prost::alloc::string::String,
    /// The hex value for background color.
    #[prost(string, tag="2")]
    pub background_color: ::prost::alloc::string::String,
    /// The hex value for warning color.
    #[prost(string, tag="3")]
    pub warn_color: ::prost::alloc::string::String,
    /// The value for font color.
    #[prost(string, tag="4")]
    pub font_color: ::prost::alloc::string::String,
    /// The URL where the logo is served.
    #[prost(string, tag="5")]
    pub logo_url: ::prost::alloc::string::String,
    /// The URL where the icon is served.
    #[prost(string, tag="6")]
    pub icon_url: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ThemeMode {
    Unspecified = 0,
    Auto = 1,
    Light = 2,
    Dark = 3,
}
impl ThemeMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "THEME_MODE_UNSPECIFIED",
            Self::Auto => "THEME_MODE_AUTO",
            Self::Light => "THEME_MODE_LIGHT",
            Self::Dark => "THEME_MODE_DARK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "THEME_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "THEME_MODE_AUTO" => Some(Self::Auto),
            "THEME_MODE_LIGHT" => Some(Self::Light),
            "THEME_MODE_DARK" => Some(Self::Dark),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainSettings {
    /// If enabled, the login name will automatically be suffixed with the domain of the organization.
    /// This ensures that the login name is unique across the instance.
    #[prost(bool, tag="1")]
    pub login_name_includes_domain: bool,
    /// If enabled, Organization Domains must be verified (through an DNS or HTTP challenge) upon creation.
    /// If disabled, Organization Domains will be created as already verified automatically.
    #[prost(bool, tag="2")]
    pub require_org_domain_verification: bool,
    /// If enabled, the SMTP sender address domain must match Custom Domain on the instance.
    #[prost(bool, tag="3")]
    pub smtp_sender_address_matches_instance_domain: bool,
    /// ResourceOwnerType returns if the setting is managed on the organization explicitly or
    /// fell back on the instance settings.
    #[prost(enumeration="ResourceOwnerType", tag="6")]
    pub resource_owner_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LegalAndSupportSettings {
    /// Link to the Terms of Service. Can be a relative or absolute URL.
    #[prost(string, tag="1")]
    pub tos_link: ::prost::alloc::string::String,
    /// Link to the Privacy Policy. Can be a relative or absolute URL.
    #[prost(string, tag="2")]
    pub privacy_policy_link: ::prost::alloc::string::String,
    /// Link to a help page. Can be a relative or absolute URL.
    #[prost(string, tag="3")]
    pub help_link: ::prost::alloc::string::String,
    /// Email address for support issues.
    #[prost(string, tag="4")]
    pub support_email: ::prost::alloc::string::String,
    /// ResourceOwnerType returns if the setting is managed on the organization explicitly or
    /// fell back on the instance settings.
    #[prost(enumeration="ResourceOwnerType", tag="5")]
    pub resource_owner_type: i32,
    /// Link to documentation to be shown in the management console.
    #[prost(string, tag="6")]
    pub docs_link: ::prost::alloc::string::String,
    /// Link to an external resource that will be available to users in the management console.
    #[prost(string, tag="7")]
    pub custom_link: ::prost::alloc::string::String,
    /// The button text that would be shown in the management console pointing to custom link.
    #[prost(string, tag="8")]
    pub custom_link_text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LockoutSettings {
    /// The amount of failed password attempts before the account gets locked.
    /// Attempts are reset as soon as the password is entered correctly or the password is reset.
    /// If set to 0 the account will never be locked.
    #[prost(uint64, tag="1")]
    pub max_password_attempts: u64,
    /// ResourceOwnerType returns if the settings is managed on the organization explicitly or
    /// fell back on the instance settings.
    #[prost(enumeration="ResourceOwnerType", tag="2")]
    pub resource_owner_type: i32,
    /// THe amount of failed OTP (TOTP, SMS, Email) attempts before the account gets locked.
    /// Attempts are reset as soon as the OTP is entered correctly.
    /// If set to 0 the account will never be locked.
    #[prost(uint64, tag="3")]
    pub max_otp_attempts: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSettings {
    /// If enabled, users can log in locally with their username and passkeys or password.
    /// Disabling this option will require users to log in with an external identity provider.
    /// Be sure to allow at least one external identity provider if this option is disabled.
    /// Deprecated: check allow_local_authentication instead.
    #[deprecated]
    #[prost(bool, tag="1")]
    pub allow_username_password: bool,
    /// If enabled, users can log in locally with their username and passkeys or password.
    /// Disabling this option will require users to log in with an external identity provider.
    /// Be sure to allow at least one external identity provider if this option is disabled.
    #[prost(bool, tag="20")]
    pub allow_local_authentication: bool,
    /// If enabled, users can register a local account by themself.
    /// This option does not effect external identity providers.
    /// Each identity provider can be configured to allow or disallow registration.
    #[prost(bool, tag="2")]
    pub allow_register: bool,
    /// If enabled, users will generally be allowed to use an external identity provider to log in.
    /// Be sure to allow at least one external identity provider if this option is enabled.
    #[prost(bool, tag="3")]
    pub allow_external_idp: bool,
    /// If enabled, users will be forced to use a multi-factor to log in.
    /// This also applies to federated logins through an external identity provider.
    /// Users will be required to set up a second factor if they have not done so already.
    #[prost(bool, tag="4")]
    pub force_mfa: bool,
    /// Defines the usage of passkeys for users.
    /// PASSKEYS_TYPE_NOT_ALLOWED: Users are not allowed to use passkeys.
    /// PASSKEYS_TYPE_ALLOWED: Users are allowed to use passkeys.
    /// There will be additional options in the future.
    /// If passkeys are allowed, users can choose to use passkeys or password for local authentication.
    /// A verified passkey authentication will not require a second factor, if force_mfa is enabled.
    #[prost(enumeration="PasskeysType", tag="5")]
    pub passkeys_type: i32,
    /// If enabled, the password reset link will be hidden on the login screen.
    #[prost(bool, tag="6")]
    pub hide_password_reset: bool,
    /// If enabled, an unknown username on the login screen will not return an error directly,
    /// but will always display the password screen.
    /// This prevents user enumeration attacks.
    #[prost(bool, tag="7")]
    pub ignore_unknown_usernames: bool,
    /// Defines where the user will be redirected to if the login is started without app context (e.g. from mail).
    #[prost(string, tag="8")]
    pub default_redirect_uri: ::prost::alloc::string::String,
    /// The duration a password check is valid.
    /// After this time has passed, the user will be required to re-validate their
    /// password on the next action that requires authentication.
    /// Note that this does not enforce a logout or session expiration.
    #[prost(message, optional, tag="9")]
    pub password_check_lifetime: ::core::option::Option<::pbjson_types::Duration>,
    /// The duration a login through an external identity provider is valid.
    /// After this time has passed, the user will be required to re-authenticate with the
    /// external identity provider on the next action that requires authentication.
    /// Note that this does not enforce a logout or session expiration.
    #[prost(message, optional, tag="10")]
    pub external_login_check_lifetime: ::core::option::Option<::pbjson_types::Duration>,
    /// Defines after how much time the mfa prompt will be shown again.
    #[prost(message, optional, tag="11")]
    pub mfa_init_skip_lifetime: ::core::option::Option<::pbjson_types::Duration>,
    /// The duration a second factor check is valid.
    /// After this time has passed, the user will be required to re-validate their
    /// second factor on the next action that requires authentication.
    /// Note that this does not enforce a logout or session expiration.
    #[prost(message, optional, tag="12")]
    pub second_factor_check_lifetime: ::core::option::Option<::pbjson_types::Duration>,
    /// The duration a multi-factor check is valid.
    /// After this time has passed, the user will be required to re-validate their
    /// multi-factor on the next action that requires authentication.
    /// Note that this does not enforce a logout or session expiration.
    #[prost(message, optional, tag="13")]
    pub multi_factor_check_lifetime: ::core::option::Option<::pbjson_types::Duration>,
    /// The list of allowed second factors.
    #[prost(enumeration="SecondFactorType", repeated, tag="14")]
    pub second_factors: ::prost::alloc::vec::Vec<i32>,
    /// The list of allowed multi factors.
    #[prost(enumeration="MultiFactorType", repeated, tag="15")]
    pub multi_factors: ::prost::alloc::vec::Vec<i32>,
    /// Allow discovery of the organization and its authentication option by domain.
    /// If set to true, the suffix (@domain.com) of an unknown username input on the login screen
    /// will be matched against the Organization Domains and will redirect to the registration of that organization on success.
    /// The registration can either be locally (requires allow_register to be true) or through an external identity provider.
    /// In case only one identity provider is configured for the organization, the user will be redirected directly to the identity provider.
    #[prost(bool, tag="16")]
    pub allow_domain_discovery: bool,
    /// By default, users can login with their verified email address additionally to their login name.
    /// Setting this to true disables the email login.
    /// Note: If the email is set as the login name, this setting has no effect.
    #[prost(bool, tag="17")]
    pub disable_login_with_email: bool,
    /// By default, users can login with their verified phone number additionally to their login name.
    /// Setting this to true disables the phone number login.
    /// Note: If the phone number is set as the login name, this setting has no effect.
    #[prost(bool, tag="18")]
    pub disable_login_with_phone: bool,
    /// ResourceOwnerType returns if the settings is managed on the organization explicitly or
    /// fell back on the instance settings.
    #[prost(enumeration="ResourceOwnerType", tag="19")]
    pub resource_owner_type: i32,
    /// If enabled, users will be forced to use a multi-factor to log in if they authenticated locally.
    /// This does not apply to federated logins through an external identity provider.
    /// Users will be required to set up a second factor if they have not done so already.
    /// If both force_mfa and force_mfa_local_only are enabled, force_mfa takes precedence and
    /// all logins will require a second factor.
    #[prost(bool, tag="22")]
    pub force_mfa_local_only: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IdentityProvider {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="IdentityProviderType", tag="3")]
    pub r#type: i32,
    #[prost(message, optional, tag="4")]
    pub options: ::core::option::Option<super::super::idp::v2::Options>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SecondFactorType {
    Unspecified = 0,
    /// Deprecated: use SECOND_FACTOR_TYPE_TOTP instead.
    Otp = 1,
    U2f = 2,
    OtpEmail = 3,
    OtpSms = 4,
    RecoveryCodes = 5,
}
impl SecondFactorType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SECOND_FACTOR_TYPE_UNSPECIFIED",
            Self::Otp => "SECOND_FACTOR_TYPE_OTP",
            Self::U2f => "SECOND_FACTOR_TYPE_U2F",
            Self::OtpEmail => "SECOND_FACTOR_TYPE_OTP_EMAIL",
            Self::OtpSms => "SECOND_FACTOR_TYPE_OTP_SMS",
            Self::RecoveryCodes => "SECOND_FACTOR_TYPE_RECOVERY_CODES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SECOND_FACTOR_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SECOND_FACTOR_TYPE_OTP" => Some(Self::Otp),
            "SECOND_FACTOR_TYPE_U2F" => Some(Self::U2f),
            "SECOND_FACTOR_TYPE_OTP_EMAIL" => Some(Self::OtpEmail),
            "SECOND_FACTOR_TYPE_OTP_SMS" => Some(Self::OtpSms),
            "SECOND_FACTOR_TYPE_RECOVERY_CODES" => Some(Self::RecoveryCodes),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MultiFactorType {
    Unspecified = 0,
    U2fWithVerification = 1,
}
impl MultiFactorType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MULTI_FACTOR_TYPE_UNSPECIFIED",
            Self::U2fWithVerification => "MULTI_FACTOR_TYPE_U2F_WITH_VERIFICATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MULTI_FACTOR_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MULTI_FACTOR_TYPE_U2F_WITH_VERIFICATION" => Some(Self::U2fWithVerification),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PasskeysType {
    NotAllowed = 0,
    Allowed = 1,
}
impl PasskeysType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotAllowed => "PASSKEYS_TYPE_NOT_ALLOWED",
            Self::Allowed => "PASSKEYS_TYPE_ALLOWED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PASSKEYS_TYPE_NOT_ALLOWED" => Some(Self::NotAllowed),
            "PASSKEYS_TYPE_ALLOWED" => Some(Self::Allowed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IdentityProviderType {
    Unspecified = 0,
    Oidc = 1,
    Jwt = 2,
    Ldap = 3,
    Oauth = 4,
    AzureAd = 5,
    Github = 6,
    GithubEs = 7,
    Gitlab = 8,
    GitlabSelfHosted = 9,
    Google = 10,
    Saml = 11,
    Apple = 12,
}
impl IdentityProviderType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "IDENTITY_PROVIDER_TYPE_UNSPECIFIED",
            Self::Oidc => "IDENTITY_PROVIDER_TYPE_OIDC",
            Self::Jwt => "IDENTITY_PROVIDER_TYPE_JWT",
            Self::Ldap => "IDENTITY_PROVIDER_TYPE_LDAP",
            Self::Oauth => "IDENTITY_PROVIDER_TYPE_OAUTH",
            Self::AzureAd => "IDENTITY_PROVIDER_TYPE_AZURE_AD",
            Self::Github => "IDENTITY_PROVIDER_TYPE_GITHUB",
            Self::GithubEs => "IDENTITY_PROVIDER_TYPE_GITHUB_ES",
            Self::Gitlab => "IDENTITY_PROVIDER_TYPE_GITLAB",
            Self::GitlabSelfHosted => "IDENTITY_PROVIDER_TYPE_GITLAB_SELF_HOSTED",
            Self::Google => "IDENTITY_PROVIDER_TYPE_GOOGLE",
            Self::Saml => "IDENTITY_PROVIDER_TYPE_SAML",
            Self::Apple => "IDENTITY_PROVIDER_TYPE_APPLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IDENTITY_PROVIDER_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "IDENTITY_PROVIDER_TYPE_OIDC" => Some(Self::Oidc),
            "IDENTITY_PROVIDER_TYPE_JWT" => Some(Self::Jwt),
            "IDENTITY_PROVIDER_TYPE_LDAP" => Some(Self::Ldap),
            "IDENTITY_PROVIDER_TYPE_OAUTH" => Some(Self::Oauth),
            "IDENTITY_PROVIDER_TYPE_AZURE_AD" => Some(Self::AzureAd),
            "IDENTITY_PROVIDER_TYPE_GITHUB" => Some(Self::Github),
            "IDENTITY_PROVIDER_TYPE_GITHUB_ES" => Some(Self::GithubEs),
            "IDENTITY_PROVIDER_TYPE_GITLAB" => Some(Self::Gitlab),
            "IDENTITY_PROVIDER_TYPE_GITLAB_SELF_HOSTED" => Some(Self::GitlabSelfHosted),
            "IDENTITY_PROVIDER_TYPE_GOOGLE" => Some(Self::Google),
            "IDENTITY_PROVIDER_TYPE_SAML" => Some(Self::Saml),
            "IDENTITY_PROVIDER_TYPE_APPLE" => Some(Self::Apple),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PasswordComplexitySettings {
    /// The minimum length a password must have.
    #[prost(uint64, tag="1")]
    pub min_length: u64,
    /// Defines if the password MUST contain an upper case letter.
    #[prost(bool, tag="2")]
    pub requires_uppercase: bool,
    /// Defines if the password MUST contain a lowercase letter.
    #[prost(bool, tag="3")]
    pub requires_lowercase: bool,
    /// Defines if the password MUST contain a number.
    #[prost(bool, tag="4")]
    pub requires_number: bool,
    /// Defines if the password MUST contain a symbol or special character. E.g. "$"
    #[prost(bool, tag="5")]
    pub requires_symbol: bool,
    /// ResourceOwnerType returns if the settings is managed on the organization explicitly or
    /// fell back on the instance settings.
    #[prost(enumeration="ResourceOwnerType", tag="6")]
    pub resource_owner_type: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PasswordExpirySettings {
    /// Amount of days after which a password will expire. The user will be forced to change the password on the following authentication.
    #[prost(uint64, tag="1")]
    pub max_age_days: u64,
    /// Amount of days after which the user should be notified of the upcoming expiry. Zitadel will not notify the user.
    #[prost(uint64, tag="2")]
    pub expire_warn_days: u64,
    /// ResourceOwnerType returns if the settings is managed on the organization explicitly or
    /// fail back on the instance settings.
    #[prost(enumeration="ResourceOwnerType", tag="3")]
    pub resource_owner_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SecuritySettings {
    /// EmbeddedIframeSettings defines if the login UI can be embedded in an iframe
    /// and which origins are allowed to do so.
    #[prost(message, optional, tag="1")]
    pub embedded_iframe: ::core::option::Option<EmbeddedIframeSettings>,
    /// If enabled, users are allowed to impersonate other users.
    /// The impersonator needs the appropriate `*_IMPERSONATOR` roles assigned as well".
    #[prost(bool, tag="2")]
    pub enable_impersonation: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmbeddedIframeSettings {
    /// Enabled states if iframe embedding is enabled or disabled.
    #[prost(bool, tag="1")]
    pub enabled: bool,
    /// AllowedOrigins defines which origins are allowed to embed Zitadel in an iframe.
    #[prost(string, repeated, tag="2")]
    pub allowed_origins: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLoginSettingsRequest {
    /// Specify the context for which the login settings should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned settings will fall back to the instance settings
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLoginSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<LoginSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPasswordComplexitySettingsRequest {
    /// Specify the context for which the password complexity settings should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned settings will fall back to the instance settings
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPasswordComplexitySettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<PasswordComplexitySettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPasswordExpirySettingsRequest {
    /// Specify the context for which the password expiry settings should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned settings will fall back to the instance settings
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPasswordExpirySettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<PasswordExpirySettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBrandingSettingsRequest {
    /// Specify the context for which the branding settings should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned settings will fall back to the instance settings
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBrandingSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<BrandingSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDomainSettingsRequest {
    /// Specify the context for which the domain settings should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned settings will fall back to the instance settings
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDomainSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<DomainSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLegalAndSupportSettingsRequest {
    /// Specify the context for which the legal and support settings should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned settings will fall back to the instance settings
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLegalAndSupportSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<LegalAndSupportSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLockoutSettingsRequest {
    /// Specify the context for which the lockout settings should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned settings will fall back to the instance settings
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLockoutSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<LockoutSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetActiveIdentityProvidersRequest {
    /// Specify the context for which the active identity providers should be returned.
    /// This can be the instance or an organization.
    /// In case of an organization, the returned providers will fall back to the instance providers
    /// if not explicitly set on the organization.
    #[prost(message, optional, tag="1")]
    pub ctx: ::core::option::Option<super::super::object::v2::RequestContext>,
    #[prost(bool, optional, tag="2")]
    pub creation_allowed: ::core::option::Option<bool>,
    #[prost(bool, optional, tag="3")]
    pub linking_allowed: ::core::option::Option<bool>,
    #[prost(bool, optional, tag="4")]
    pub auto_creation: ::core::option::Option<bool>,
    #[prost(bool, optional, tag="5")]
    pub auto_linking: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveIdentityProvidersResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::ListDetails>,
    #[prost(message, repeated, tag="2")]
    pub identity_providers: ::prost::alloc::vec::Vec<IdentityProvider>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGeneralSettingsRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGeneralSettingsResponse {
    /// The unique identifier of the default organization.
    /// The default organization is used to assign new users to an organization if no other organization is specified.
    /// Deprecated: use default_organization_id instead.
    #[prost(string, tag="1")]
    pub default_org_id: ::prost::alloc::string::String,
    /// The default language is use if no other language is specified or detected.
    /// The format is a BCP 47 language tag (e.g. "en", "de", "fr-CH").
    #[prost(string, tag="2")]
    pub default_language: ::prost::alloc::string::String,
    /// The list of supported languages.
    /// Note that the instance might restrict the languages further
    /// only allowing a subset of these languages to be used.
    /// The format is a BCP 47 language tag (e.g. "en", "de", "fr-CH").
    #[prost(string, repeated, tag="3")]
    pub supported_languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The unique identifier of the default organization.
    /// The default organization is used to assign new users to an organization if no other organization is specified.
    #[prost(string, tag="4")]
    pub default_organization_id: ::prost::alloc::string::String,
    /// The list of allowed languages for the instance.
    /// This is a subset of the supported languages to be used in the instance
    /// e.g. for user selection during registration or language detection in the UI.
    /// The format is a BCP 47 language tag (e.g. "en", "de", "fr-CH").
    #[prost(string, repeated, tag="5")]
    pub allowed_languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSecuritySettingsRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSecuritySettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<SecuritySettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetSecuritySettingsRequest {
    /// EmbeddedIframeSettings defines if the login UI can be embedded in an iframe
    /// and which origins are allowed to do so.
    #[prost(message, optional, tag="1")]
    pub embedded_iframe: ::core::option::Option<EmbeddedIframeSettings>,
    /// If enabled, users are allowed to impersonate other users.
    /// The impersonator needs the appropriate `*_IMPERSONATOR` roles assigned as well".
    #[prost(bool, tag="2")]
    pub enable_impersonation: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetSecuritySettingsResponse {
    #[prost(message, optional, tag="1")]
    pub details: ::core::option::Option<super::super::object::v2::Details>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetHostedLoginTranslationRequest {
    /// The locale of the translations to be returned.
    /// Needs to be a BCP 47 language tag (e.g. "en", "de", "fr-CH").
    #[prost(string, tag="4")]
    pub locale: ::prost::alloc::string::String,
    /// if set to true, higher levels are ignored, if false higher levels are merged into the file
    #[prost(bool, tag="5")]
    pub ignore_inheritance: bool,
    /// Specify the level from which the translation should be returned.
    /// If the requested level doesn't contain all translations, and ignore_inheritance is set to false
    /// a merging process fallbacks onto the higher levels ensuring all keys in the file have a translation.
    #[prost(oneof="get_hosted_login_translation_request::Level", tags="1, 2, 3")]
    pub level: ::core::option::Option<get_hosted_login_translation_request::Level>,
}
/// Nested message and enum types in `GetHostedLoginTranslationRequest`.
pub mod get_hosted_login_translation_request {
    /// Specify the level from which the translation should be returned.
    /// If the requested level doesn't contain all translations, and ignore_inheritance is set to false
    /// a merging process fallbacks onto the higher levels ensuring all keys in the file have a translation.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Level {
        #[prost(bool, tag="1")]
        System(bool),
        #[prost(bool, tag="2")]
        Instance(bool),
        #[prost(string, tag="3")]
        OrganizationId(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHostedLoginTranslationResponse {
    /// hash of the payload
    #[prost(string, tag="1")]
    pub etag: ::prost::alloc::string::String,
    /// Translations contains the translations in the requested language.
    #[prost(message, optional, tag="2")]
    pub translations: ::core::option::Option<::pbjson_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetHostedLoginTranslationRequest {
    /// The locale of the translations to be set.
    /// Needs to be a BCP 47 language tag (e.g. "en", "de", "fr-CH").
    #[prost(string, tag="3")]
    pub locale: ::prost::alloc::string::String,
    /// Translations should contain the translations in the specified locale.
    #[prost(message, optional, tag="4")]
    pub translations: ::core::option::Option<::pbjson_types::Struct>,
    /// Specify the level on which the translation should be set.
    /// Only instance or organization level is allowed.
    /// System level translations can't be modified.
    /// In case of organization level, the organization_id needs to be set.
    /// If a translation already exists on the specified level, it will be overwritten.
    #[prost(oneof="set_hosted_login_translation_request::Level", tags="1, 2")]
    pub level: ::core::option::Option<set_hosted_login_translation_request::Level>,
}
/// Nested message and enum types in `SetHostedLoginTranslationRequest`.
pub mod set_hosted_login_translation_request {
    /// Specify the level on which the translation should be set.
    /// Only instance or organization level is allowed.
    /// System level translations can't be modified.
    /// In case of organization level, the organization_id needs to be set.
    /// If a translation already exists on the specified level, it will be overwritten.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Level {
        #[prost(bool, tag="1")]
        Instance(bool),
        #[prost(string, tag="2")]
        OrganizationId(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetHostedLoginTranslationResponse {
    /// hash of the saved translation. Valid only when ignore_inheritance = true
    #[prost(string, tag="1")]
    pub etag: ::prost::alloc::string::String,
}
include!("zitadel.settings.v2.tonic.rs");
// @@protoc_insertion_point(module)